/* ============================================================
   DATOS · ALEMÁN
   Extraído de las Lecciones 01–14 de Idiomas/Aleman
   n = nivel: 1 fácil · 2 intermedio · 3 difícil
   ============================================================ */

window.ALEMAN = {

/* ---------- SUSTANTIVOS CON GÉNERO ---------- */
sustantivos: [
  /* nivel 1 — terminaciones con regla fiable */
  {w:"Wohnung",       g:"die", es:"el piso, la vivienda", pista:"-ung → siempre die", n:1},
  {w:"Zeitung",       g:"die", es:"el periódico",         pista:"-ung → siempre die", n:1},
  {w:"Übung",         g:"die", es:"el ejercicio",         pista:"-ung → siempre die", n:1},
  {w:"Prüfung",       g:"die", es:"el examen",            pista:"-ung → siempre die", n:1},
  {w:"Freiheit",      g:"die", es:"la libertad",          pista:"-heit → siempre die", n:1},
  {w:"Krankheit",     g:"die", es:"la enfermedad",        pista:"-heit → siempre die", n:1},
  {w:"Möglichkeit",   g:"die", es:"la posibilidad",       pista:"-keit → siempre die", n:1},
  {w:"Schwierigkeit", g:"die", es:"la dificultad",        pista:"-keit → siempre die", n:1},
  {w:"Freundschaft",  g:"die", es:"la amistad",           pista:"-schaft → siempre die", n:1},
  {w:"Mannschaft",    g:"die", es:"el equipo",            pista:"-schaft → siempre die", n:1},
  {w:"Nation",        g:"die", es:"la nación",            pista:"-ion → siempre die", n:1},
  {w:"Universität",   g:"die", es:"la universidad",       pista:"-tät → siempre die", n:1},
  {w:"Familie",       g:"die", es:"la familia",           pista:"-ie → siempre die", n:1},
  {w:"Mädchen",       g:"das", es:"la chica",             pista:"-chen es diminutivo → das", n:1},
  {w:"Brötchen",      g:"das", es:"el panecillo",         pista:"-chen es diminutivo → das", n:1},
  {w:"Büchlein",      g:"das", es:"el librito",           pista:"-lein es diminutivo → das", n:1},
  {w:"Zentrum",       g:"das", es:"el centro",            pista:"-um → siempre das", n:1},
  {w:"Museum",        g:"das", es:"el museo",             pista:"-um → siempre das", n:1},
  {w:"Datum",         g:"das", es:"la fecha",             pista:"-um → siempre das", n:1},
  {w:"Dokument",      g:"das", es:"el documento",         pista:"-ment → siempre das", n:1},
  {w:"Instrument",    g:"das", es:"el instrumento",       pista:"-ment → siempre das", n:1},
  {w:"Essen",         g:"das", es:"la comida",            pista:"infinitivo sustantivado → das", n:1},
  {w:"Leben",         g:"das", es:"la vida",              pista:"infinitivo sustantivado → das", n:1},
  {w:"Lehrer",        g:"der", es:"el profesor",          pista:"-er de persona que hace algo → der", n:1},
  {w:"Bäcker",        g:"der", es:"el panadero",          pista:"-er de persona que hace algo → der", n:1},
  {w:"Computer",      g:"der", es:"el ordenador",         pista:"-er → der", n:1},
  {w:"Frühling",      g:"der", es:"la primavera",         pista:"-ling → der", n:1},
  {w:"Schmetterling", g:"der", es:"la mariposa",          pista:"-ling → der", n:1},
  {w:"Kapitalismus",  g:"der", es:"el capitalismo",       pista:"-ismus → der", n:1},
  {w:"Tourismus",     g:"der", es:"el turismo",           pista:"-ismus → der", n:1},
  {w:"Montag",        g:"der", es:"el lunes",             pista:"días de la semana → der", n:1},
  {w:"Januar",        g:"der", es:"enero",                pista:"meses → der", n:1},
  {w:"Sommer",        g:"der", es:"el verano",            pista:"estaciones → der", n:1},
  {w:"Regen",         g:"der", es:"la lluvia",            pista:"clima → der", n:1},
  {w:"Schnee",        g:"der", es:"la nieve",             pista:"clima → der", n:1},
  {w:"Wind",          g:"der", es:"el viento",            pista:"clima → der", n:1},

  /* nivel 2 — vocabulario cotidiano sin regla */
  {w:"Vater",     g:"der", es:"el padre",      n:2},
  {w:"Mutter",    g:"die", es:"la madre",      n:2},
  {w:"Sohn",      g:"der", es:"el hijo",       n:2},
  {w:"Tochter",   g:"die", es:"la hija",       n:2},
  {w:"Bruder",    g:"der", es:"el hermano",    n:2},
  {w:"Schwester", g:"die", es:"la hermana",    n:2},
  {w:"Kind",      g:"das", es:"el niño",       n:2, pista:"neutro, aunque en español sea masculino"},
  {w:"Freund",    g:"der", es:"el amigo/novio",n:2},
  {w:"Zeit",      g:"die", es:"el tiempo",     n:2},
  {w:"Auto",      g:"das", es:"el coche",      n:2},
  {w:"Frage",     g:"die", es:"la pregunta",   n:2},
  {w:"Hund",      g:"der", es:"el perro",      n:2},
  {w:"Katze",     g:"die", es:"el gato",       n:2},
  {w:"Geld",      g:"das", es:"el dinero",     n:2},
  {w:"Arbeit",    g:"die", es:"el trabajo",    n:2},
  {w:"Tisch",     g:"der", es:"la mesa",       n:2},
  {w:"Lampe",     g:"die", es:"la lámpara",    n:2},
  {w:"Blume",     g:"die", es:"la flor",       n:2},
  {w:"Schule",    g:"die", es:"la escuela",    n:2},
  {w:"Haus",      g:"das", es:"la casa",       n:2},
  {w:"Buch",      g:"das", es:"el libro",      n:2},
  {w:"Wasser",    g:"das", es:"el agua",       n:2},
  {w:"Kaffee",    g:"der", es:"el café",       n:2},
  {w:"Brot",      g:"das", es:"el pan",        n:2},
  {w:"Käse",      g:"der", es:"el queso",      n:2},
  {w:"Stadt",     g:"die", es:"la ciudad",     n:2},
  {w:"Film",      g:"der", es:"la película",   n:2},
  {w:"Stuhl",     g:"der", es:"la silla",      n:2},
  {w:"Schlüssel", g:"der", es:"la llave",      n:2},
  {w:"Apfel",     g:"der", es:"la manzana",    n:2},
  {w:"Zimmer",    g:"das", es:"la habitación", n:2},
  {w:"Bus",       g:"der", es:"el autobús",    n:2},
  {w:"Zug",       g:"der", es:"el tren",       n:2},
  {w:"Nacht",     g:"die", es:"la noche",      n:2},
  {w:"Abend",     g:"der", es:"la tarde/noche",n:2},
  {w:"Morgen",    g:"der", es:"la mañana",     n:2},
  {w:"Tag",       g:"der", es:"el día",        n:2},
  {w:"Woche",     g:"die", es:"la semana",     n:2},
  {w:"Jahr",      g:"das", es:"el año",        n:2},
  {w:"Park",      g:"der", es:"el parque",     n:2},
  {w:"Bett",      g:"das", es:"la cama",       n:2},
  {w:"Suppe",     g:"die", es:"la sopa",       n:2},
  {w:"Tür",       g:"die", es:"la puerta",     n:2},
  {w:"Garten",    g:"der", es:"el jardín",     n:2},
  {w:"Baum",      g:"der", es:"el árbol",      n:2},
  {w:"Straße",    g:"die", es:"la calle",      n:2},
  {w:"Sprache",   g:"die", es:"el idioma",     n:2},
  {w:"Musik",     g:"die", es:"la música",     n:2},
  {w:"Gitarre",   g:"die", es:"la guitarra",   n:2},
  {w:"Fahrrad",   g:"das", es:"la bicicleta",  n:2},
  {w:"Büro",      g:"das", es:"la oficina",    n:2},
  {w:"Wetter",    g:"das", es:"el tiempo (clima)", n:2},
  {w:"Problem",   g:"das", es:"el problema",   n:2},
  {w:"Schokolade",g:"die", es:"el chocolate",  n:2},
  {w:"Brief",     g:"der", es:"la carta",      n:2},
  {w:"Supermarkt",g:"der", es:"el supermercado", n:2},

  /* nivel 3 — trampas y falsos amigos */
  {w:"Sonne",   g:"die", es:"el sol",        pista:"¡en alemán el sol es FEMENINO!", n:3},
  {w:"Mond",    g:"der", es:"la luna",       pista:"¡en alemán la luna es MASCULINA!", n:3},
  {w:"Fenster", g:"das", es:"la ventana",    n:3},
  {w:"Gift",    g:"das", es:"el veneno",     pista:"falso amigo: NO es 'regalo' (das Geschenk)", n:3},
  {w:"Rat",     g:"der", es:"el consejo",    pista:"falso amigo: NO es 'rata' (die Ratte)", n:3},
  {w:"Ratte",   g:"die", es:"la rata",       n:3},
  {w:"Geschenk",g:"das", es:"el regalo",     n:3},
  {w:"Handy",   g:"das", es:"el móvil",      pista:"préstamo del inglés, pero es neutro", n:3},
  {w:"Karte",   g:"die", es:"la tarjeta / el mapa", n:3},
  {w:"Chef",    g:"der", es:"el jefe",       pista:"falso amigo: NO es 'cocinero' (der Koch)", n:3},
  {w:"Koch",    g:"der", es:"el cocinero",   n:3},
  {w:"Wagen",   g:"der", es:"el auto",       n:3},
  {w:"Hunger",  g:"der", es:"el hambre",     n:3},
  {w:"Durst",   g:"der", es:"la sed",        n:3},
  {w:"Angst",   g:"die", es:"el miedo",      n:3},
  {w:"Fußball", g:"der", es:"el fútbol",     n:3},
  {w:"Sport",   g:"der", es:"el deporte",    n:3},
  {w:"Pause",   g:"die", es:"la pausa",      n:3},
  {w:"Medizin", g:"die", es:"la medicina",   n:3},
  {w:"Laptop",  g:"der", es:"el portátil",   n:3},
  {w:"Wein",    g:"der", es:"el vino",       n:3},
  {w:"Bier",    g:"das", es:"la cerveza",    n:3},
  {w:"Milch",   g:"die", es:"la leche",      n:3},
  {w:"Ei",      g:"das", es:"el huevo",      n:3},
  {w:"Fleisch", g:"das", es:"la carne",      n:3},
  {w:"Zucker",  g:"der", es:"el azúcar",     n:3},
  {w:"Frau",    g:"die", es:"la mujer/esposa/señora", n:3},
  {w:"Mann",    g:"der", es:"el hombre/marido", n:3}
],

/* ---------- CONJUGACIÓN ---------- */
pronombres: ["ich","du","er/sie/es","wir","ihr","sie/Sie"],

verbos: [
  {inf:"sein",   es:"ser / estar",  f:["bin","bist","ist","sind","seid","sind"], n:1, nota:"El verbo más irregular. Solo hay 4 formas: bin · bist · ist · sind (+ seid)."},
  {inf:"haben",  es:"tener",        f:["habe","hast","hat","haben","habt","haben"], n:1, nota:"du y er pierden la -b-: hast, hat."},
  {inf:"wohnen", es:"vivir/residir",f:["wohne","wohnst","wohnt","wohnen","wohnt","wohnen"], n:1},
  {inf:"spielen",es:"jugar/tocar",  f:["spiele","spielst","spielt","spielen","spielt","spielen"], n:1},
  {inf:"lernen", es:"aprender",     f:["lerne","lernst","lernt","lernen","lernt","lernen"], n:1},
  {inf:"kommen", es:"venir",        f:["komme","kommst","kommt","kommen","kommt","kommen"], n:1},
  {inf:"machen", es:"hacer",        f:["mache","machst","macht","machen","macht","machen"], n:1},
  {inf:"trinken",es:"beber",        f:["trinke","trinkst","trinkt","trinken","trinkt","trinken"], n:1},
  {inf:"kaufen", es:"comprar",      f:["kaufe","kaufst","kauft","kaufen","kauft","kaufen"], n:1},
  {inf:"sagen",  es:"decir",        f:["sage","sagst","sagt","sagen","sagt","sagen"], n:1},
  {inf:"fragen", es:"preguntar",    f:["frage","fragst","fragt","fragen","fragt","fragen"], n:1},
  {inf:"hören",  es:"oír",          f:["höre","hörst","hört","hören","hört","hören"], n:1},
  {inf:"brauchen",es:"necesitar",   f:["brauche","brauchst","braucht","brauchen","braucht","brauchen"], n:1},
  {inf:"kochen", es:"cocinar",      f:["koche","kochst","kocht","kochen","kocht","kochen"], n:1},
  {inf:"lieben", es:"amar",         f:["liebe","liebst","liebt","lieben","liebt","lieben"], n:1},
  {inf:"leben",  es:"vivir (estar vivo)", f:["lebe","lebst","lebt","leben","lebt","leben"], n:1},
  {inf:"studieren",es:"estudiar en la uni", f:["studiere","studierst","studiert","studieren","studiert","studieren"], n:1},

  {inf:"arbeiten",es:"trabajar",  f:["arbeite","arbeitest","arbeitet","arbeiten","arbeitet","arbeiten"], n:2, nota:"Raíz en -t → se añade una -e- de apoyo: du arbeitest, er arbeitet."},
  {inf:"finden",  es:"encontrar", f:["finde","findest","findet","finden","findet","finden"], n:2, nota:"Raíz en -d → -e- de apoyo: du findest."},
  {inf:"öffnen",  es:"abrir",     f:["öffne","öffnest","öffnet","öffnen","öffnet","öffnen"], n:2, nota:"Raíz en consonante+n → -e- de apoyo."},
  {inf:"warten",  es:"esperar",   f:["warte","wartest","wartet","warten","wartet","warten"], n:2, nota:"Raíz en -t → -e- de apoyo."},
  {inf:"reden",   es:"hablar/charlar", f:["rede","redest","redet","reden","redet","reden"], n:2, nota:"Raíz en -d → -e- de apoyo."},
  {inf:"heißen",  es:"llamarse",  f:["heiße","heißt","heißt","heißen","heißt","heißen"], n:2, nota:"Raíz en -ß → du pierde la s: du heißt (nunca heißst)."},
  {inf:"reisen",  es:"viajar",    f:["reise","reist","reist","reisen","reist","reisen"], n:2, nota:"Raíz en -s → du pierde la s: du reist."},
  {inf:"tanzen",  es:"bailar",    f:["tanze","tanzt","tanzt","tanzen","tanzt","tanzen"], n:2, nota:"Raíz en -z → du pierde la s: du tanzt."},

  {inf:"können", es:"poder / saber", f:["kann","kannst","kann","können","könnt","können"], n:3, modal:true, nota:"Modal: ich y er/sie/es son idénticos y sin terminación."},
  {inf:"wollen", es:"querer",        f:["will","willst","will","wollen","wollt","wollen"], n:3, modal:true, nota:"¡Ojo! ich will = YO QUIERO, no es el futuro inglés."},
  {inf:"müssen", es:"tener que",     f:["muss","musst","muss","müssen","müsst","müssen"], n:3, modal:true},
  {inf:"dürfen", es:"tener permiso", f:["darf","darfst","darf","dürfen","dürft","dürfen"], n:3, modal:true, nota:"nicht dürfen = estar prohibido."},
  {inf:"sollen", es:"deber (consejo)", f:["soll","sollst","soll","sollen","sollt","sollen"], n:3, modal:true},
  {inf:"möchten",es:"querría / me gustaría", f:["möchte","möchtest","möchte","möchten","möchtet","möchten"], n:3, modal:true, nota:"El wollen educado. Úsalo en tiendas y restaurantes."}
],

/* ---------- PARTIZIP II ---------- */
partizip: [
  {inf:"machen", p2:"gemacht",   aux:"haben", es:"hacer", n:1},
  {inf:"spielen",p2:"gespielt",  aux:"haben", es:"jugar", n:1},
  {inf:"lernen", p2:"gelernt",   aux:"haben", es:"aprender", n:1},
  {inf:"kaufen", p2:"gekauft",   aux:"haben", es:"comprar", n:1},
  {inf:"wohnen", p2:"gewohnt",   aux:"haben", es:"residir", n:1},
  {inf:"sagen",  p2:"gesagt",    aux:"haben", es:"decir", n:1},
  {inf:"hören",  p2:"gehört",    aux:"haben", es:"oír", n:1},
  {inf:"fragen", p2:"gefragt",   aux:"haben", es:"preguntar", n:1},
  {inf:"arbeiten",p2:"gearbeitet",aux:"haben",es:"trabajar", n:2, nota:"raíz en -t → -et"},
  {inf:"warten", p2:"gewartet",  aux:"haben", es:"esperar", n:2, nota:"raíz en -t → -et"},
  {inf:"reden",  p2:"geredet",   aux:"haben", es:"charlar", n:2, nota:"raíz en -d → -et"},
  {inf:"öffnen", p2:"geöffnet",  aux:"haben", es:"abrir", n:2, nota:"consonante+n → -et"},
  {inf:"essen",  p2:"gegessen",  aux:"haben", es:"comer", n:2},
  {inf:"trinken",p2:"getrunken", aux:"haben", es:"beber", n:2},
  {inf:"sehen",  p2:"gesehen",   aux:"haben", es:"ver", n:2},
  {inf:"lesen",  p2:"gelesen",   aux:"haben", es:"leer", n:2},
  {inf:"schreiben",p2:"geschrieben",aux:"haben",es:"escribir", n:2},
  {inf:"sprechen",p2:"gesprochen",aux:"haben",es:"hablar", n:2},
  {inf:"nehmen", p2:"genommen",  aux:"haben", es:"tomar", n:2},
  {inf:"schlafen",p2:"geschlafen",aux:"haben",es:"dormir", n:2},
  {inf:"finden", p2:"gefunden",  aux:"haben", es:"encontrar", n:2},
  {inf:"gehen",  p2:"gegangen",  aux:"sein",  es:"ir", n:2, nota:"movimiento A→B → sein"},
  {inf:"fahren", p2:"gefahren",  aux:"sein",  es:"ir en vehículo", n:2, nota:"movimiento A→B → sein"},
  {inf:"kommen", p2:"gekommen",  aux:"sein",  es:"venir", n:2, nota:"movimiento A→B → sein"},
  {inf:"bleiben",p2:"geblieben", aux:"sein",  es:"quedarse", n:3, nota:"excepción fija: no hay movimiento pero lleva sein"},
  {inf:"sein",   p2:"gewesen",   aux:"sein",  es:"ser/estar", n:3, nota:"excepción fija: sein + gewesen"},
  {inf:"studieren",p2:"studiert",aux:"haben", es:"estudiar (uni)", n:3, nota:"verbos en -ieren: SIN ge-"},
  {inf:"telefonieren",p2:"telefoniert",aux:"haben",es:"telefonear", n:3, nota:"verbos en -ieren: SIN ge-"},
  {inf:"fotografieren",p2:"fotografiert",aux:"haben",es:"fotografiar", n:3, nota:"verbos en -ieren: SIN ge-"},
  {inf:"reparieren",p2:"repariert",aux:"haben",es:"reparar", n:3, nota:"verbos en -ieren: SIN ge-"},
  {inf:"besuchen",p2:"besucht",  aux:"haben", es:"visitar", n:3, nota:"prefijo inseparable be- → SIN ge-"},
  {inf:"bezahlen",p2:"bezahlt",  aux:"haben", es:"pagar", n:3, nota:"prefijo inseparable be- → SIN ge-"},
  {inf:"verkaufen",p2:"verkauft",aux:"haben", es:"vender", n:3, nota:"prefijo inseparable ver- → SIN ge-"},
  {inf:"verstehen",p2:"verstanden",aux:"haben",es:"entender", n:3, nota:"prefijo inseparable ver- → SIN ge-"},
  {inf:"erklären",p2:"erklärt",  aux:"haben", es:"explicar", n:3, nota:"prefijo inseparable er- → SIN ge-"},
  {inf:"zerstören",p2:"zerstört",aux:"haben", es:"destruir", n:3, nota:"prefijo inseparable zer- → SIN ge-"},
  {inf:"aufstehen",p2:"aufgestanden",aux:"sein",es:"levantarse", n:3, sep:true, nota:"separable: el ge- va EN MEDIO. Cambio de estado → sein"},
  {inf:"einkaufen",p2:"eingekauft",aux:"haben",es:"hacer la compra", n:3, sep:true, nota:"separable: el ge- va EN MEDIO"},
  {inf:"anrufen", p2:"angerufen",aux:"haben", es:"llamar por teléfono", n:3, sep:true, nota:"separable: el ge- va EN MEDIO"},
  {inf:"fernsehen",p2:"ferngesehen",aux:"haben",es:"ver la tele", n:3, sep:true, nota:"separable: el ge- va EN MEDIO"},
  {inf:"mitkommen",p2:"mitgekommen",aux:"sein",es:"venir con alguien", n:3, sep:true, nota:"separable + movimiento → sein"},
  {inf:"ankommen",p2:"angekommen",aux:"sein",es:"llegar", n:3, sep:true, nota:"separable + movimiento → sein"},
  {inf:"aufräumen",p2:"aufgeräumt",aux:"haben",es:"ordenar", n:3, sep:true},
  {inf:"einladen",p2:"eingeladen",aux:"haben",es:"invitar", n:3, sep:true},
  {inf:"anfangen",p2:"angefangen",aux:"haben",es:"empezar", n:3, sep:true},
  {inf:"abfahren",p2:"abgefahren",aux:"sein", es:"salir (tren/bus)", n:3, sep:true}
],

/* ---------- VOCABULARIO ES ⇄ DE ---------- */
vocab: [
  {de:"Hallo", es:"hola", n:1},
  {de:"Guten Morgen", es:"buenos días (mañana)", n:1},
  {de:"Guten Tag", es:"buenos días / buenas", n:1},
  {de:"Guten Abend", es:"buenas tardes/noches", n:1},
  {de:"Tschüss", es:"chao", n:1},
  {de:"Auf Wiedersehen", es:"hasta la vista", n:1},
  {de:"Danke", es:"gracias", n:1},
  {de:"Bitte", es:"por favor / de nada", n:1},
  {de:"Ja", es:"sí", n:1},
  {de:"Nein", es:"no", n:1},
  {de:"Entschuldigung", es:"perdón / disculpe", n:1},
  {de:"müde", es:"cansado", n:1},
  {de:"nett", es:"amable", n:1, nota:"falso amigo: NO es 'neto'"},
  {de:"kalt", es:"frío", n:1},
  {de:"warm", es:"cálido", n:1},
  {de:"groß", es:"grande / alto", n:1},
  {de:"klein", es:"pequeño", n:1},
  {de:"glücklich", es:"feliz", n:1},
  {de:"sehr", es:"muy", n:1},
  {de:"auch", es:"también", n:1},
  {de:"schnell", es:"rápido", n:1},
  {de:"gern", es:"con gusto", n:1},
  {de:"heute", es:"hoy", n:1},
  {de:"morgen", es:"mañana", n:1},
  {de:"gestern", es:"ayer", n:1},
  {de:"immer", es:"siempre", n:2},
  {de:"manchmal", es:"a veces", n:2},
  {de:"früh", es:"temprano", n:2},
  {de:"spät", es:"tarde", n:2},
  {de:"viel", es:"mucho", n:2},
  {de:"ein bisschen", es:"un poco", n:2},
  {de:"zuerst", es:"primero", n:2},
  {de:"dann", es:"luego", n:2},
  {de:"danach", es:"después", n:2},
  {de:"schließlich", es:"finalmente", n:2},
  {de:"wer", es:"quién", n:1, nota:"¡no es 'where'!"},
  {de:"was", es:"qué", n:1},
  {de:"wo", es:"dónde", n:1, nota:"¡no es 'who'!"},
  {de:"wohin", es:"adónde", n:2},
  {de:"woher", es:"de dónde", n:2},
  {de:"wann", es:"cuándo", n:2},
  {de:"wie", es:"cómo", n:1},
  {de:"warum", es:"por qué", n:2},
  {de:"wie viele", es:"cuántos", n:2},
  /* números */
  {de:"null", es:"cero", n:1},
  {de:"eins", es:"uno", n:1},
  {de:"zwei", es:"dos", n:1},
  {de:"drei", es:"tres", n:1},
  {de:"vier", es:"cuatro", n:1},
  {de:"fünf", es:"cinco", n:1},
  {de:"sechs", es:"seis", n:1},
  {de:"sieben", es:"siete", n:1},
  {de:"acht", es:"ocho", n:1},
  {de:"neun", es:"nueve", n:1},
  {de:"zehn", es:"diez", n:1},
  {de:"elf", es:"once", n:2},
  {de:"zwölf", es:"doce", n:2},
  {de:"dreizehn", es:"trece", n:2},
  {de:"sechzehn", es:"dieciséis", n:3, nota:"irregular: pierde la -s de sechs"},
  {de:"siebzehn", es:"diecisiete", n:3, nota:"irregular: pierde el -en de sieben"},
  {de:"zwanzig", es:"veinte", n:2},
  /* familia y personas */
  {de:"die Eltern", es:"los padres", n:1},
  {de:"die Geschwister", es:"los hermanos (en conjunto)", n:2},
  {de:"der Großvater", es:"el abuelo", n:1},
  {de:"die Großmutter", es:"la abuela", n:1},
  {de:"der Onkel", es:"el tío", n:2},
  {de:"die Tante", es:"la tía", n:2},
  {de:"der Cousin", es:"el primo", n:2},
  {de:"die Freundin", es:"la amiga / la novia", n:2},
  /* profesiones */
  {de:"der Lehrer", es:"el profesor", n:1},
  {de:"die Lehrerin", es:"la profesora", n:1},
  {de:"der Arzt", es:"el médico", n:2},
  {de:"die Ärztin", es:"la médica", n:2},
  {de:"der Ingenieur", es:"el ingeniero", n:2},
  {de:"der Student", es:"el estudiante universitario", n:2},
  {de:"der Anwalt", es:"el abogado", n:3},
  {de:"der Verkäufer", es:"el vendedor", n:3},
  {de:"der Koch", es:"el cocinero", n:2},
  {de:"der Kellner", es:"el camarero", n:2},
  {de:"der Programmierer", es:"el programador", n:3},
  {de:"die Krankenschwester", es:"la enfermera", n:3},
  {de:"der Polizist", es:"el policía", n:2},
  {de:"der Rentner", es:"el jubilado", n:3},
  {de:"arbeitslos", es:"desempleado", n:3},
  /* países */
  {de:"Deutschland", es:"Alemania", n:1},
  {de:"Österreich", es:"Austria", n:2},
  {de:"die Schweiz", es:"Suiza", n:2, nota:"uno de los pocos países con artículo"},
  {de:"Spanien", es:"España", n:1},
  {de:"Frankreich", es:"Francia", n:2},
  {de:"England", es:"Inglaterra", n:2},
  {de:"Deutsch", es:"alemán (idioma)", n:1},
  {de:"Spanisch", es:"español (idioma)", n:1},
  {de:"Englisch", es:"inglés (idioma)", n:1},
  /* verbos y expresiones */
  {de:"Ich heiße…", es:"me llamo…", n:1},
  {de:"Wie heißt du?", es:"¿cómo te llamas?", n:1},
  {de:"Ich komme aus Chile.", es:"vengo de Chile", n:1},
  {de:"Woher kommst du?", es:"¿de dónde vienes?", n:1},
  {de:"Wie geht's?", es:"¿cómo estás?", n:1},
  {de:"Mir geht es gut.", es:"estoy bien", n:1},
  {de:"Wie alt bist du?", es:"¿cuántos años tienes?", n:2},
  {de:"Ich bin 25 Jahre alt.", es:"tengo 25 años", n:2, nota:"con SEIN, nunca con haben"},
  {de:"Ich habe Hunger.", es:"tengo hambre", n:2, nota:"aquí sí es haben"},
  {de:"duschen", es:"ducharse", n:2},
  {de:"frühstücken", es:"desayunar", n:2},
  {de:"aufstehen", es:"levantarse", n:2},
  {de:"einkaufen", es:"hacer la compra", n:2},
  {de:"anrufen", es:"llamar por teléfono", n:2},
  {de:"fernsehen", es:"ver la tele", n:2},
  {de:"mitkommen", es:"venir (con alguien)", n:3},
  {de:"ankommen", es:"llegar", n:3},
  {de:"abfahren", es:"salir (un tren)", n:3},
  {de:"anfangen", es:"empezar", n:3},
  {de:"aufräumen", es:"ordenar la casa", n:3},
  {de:"einladen", es:"invitar", n:3},
  {de:"zurückkommen", es:"volver", n:3},
  {de:"bekommen", es:"recibir", n:3, nota:"¡falso amigo! NO es 'become'"},
  {de:"helfen", es:"ayudar", n:2, nota:"rige DATIVO"},
  {de:"danken", es:"agradecer", n:2, nota:"rige DATIVO"},
  {de:"gefallen", es:"gustar (agradar)", n:2, nota:"rige DATIVO"},
  {de:"gehören", es:"pertenecer", n:3, nota:"rige DATIVO"},
  {de:"schmecken", es:"saber (comida)", n:3, nota:"rige DATIVO"},
  {de:"am Morgen", es:"por la mañana", n:2},
  {de:"am Abend", es:"por la tarde/noche", n:2},
  {de:"um halb acht", es:"a las 7:30", n:3, nota:"¡'media hacia las 8' = 7:30, no 8:30!"},
  {de:"um Viertel nach sieben", es:"a las 7:15", n:3},
  {de:"um Viertel vor acht", es:"a las 7:45", n:3},
  {de:"doch", es:"¡sí que…! (contradice una pregunta negativa)", n:3}
],

/* ---------- FRASES PARA ORDENAR ---------- */
frases: [
  {sol:"Ich heiße Joaquín.", es:"Me llamo Joaquín.", nota:"Verbo en 2ª posición, y <i>heißen</i> se escribe con ß tras vocal larga.", n:1},
  {sol:"Ich komme aus Chile.", es:"Vengo de Chile.", nota:"<b>aus</b> siempre rige Dativ, pero con países sin artículo no se nota.", n:1},
  {sol:"Wie geht es dir?", alt:["Wie geht's dir?"], es:"¿Cómo estás?", nota:"<b>dir</b> es Dativ: literalmente «¿cómo te va a ti?».", n:1},
  {sol:"Das ist mein Bruder.", es:"Este es mi hermano.", nota:"Frase con <i>sein</i>: el atributo va en Nominativ, no en Akkusativ.", n:1},
  {sol:"Ich habe einen Hund.", es:"Tengo un perro.", nota:"<b>einen</b>: Hund es masculino y es objeto directo ⟹ Akkusativ.", n:1},
  {sol:"Wir trinken gern Kaffee.", es:"Nos gusta tomar café.", nota:"<b>gern</b> + verbo es la forma normal de decir «me gusta hacer algo».", n:1},
  {sol:"Sie wohnt in Berlin.", es:"Ella vive en Berlín.", nota:"<b>in</b> + Dativ porque es ubicación (<i>wo?</i>), no movimiento.", n:1},
  {sol:"Der Kaffee ist sehr gut.", es:"El café está muy bueno.", nota:"Los adjetivos como predicado <b>no se declinan</b>: solo se declinan delante de un sustantivo.", n:1},

  {sol:"Heute gehe ich ins Kino.", alt:["Ich gehe heute ins Kino."], es:"Hoy voy al cine.", nota:"Verbo en 2ª posición: si <b>Heute</b> ocupa el puesto 1, el sujeto salta detrás del verbo (inversión).", n:1},
  {sol:"Morgen arbeite ich in Berlin.", alt:["Ich arbeite morgen in Berlin."], es:"Mañana trabajo en Berlín.", nota:"Inversión obligatoria. ❌ <i>Morgen ich arbeite…</i>", n:1},
  {sol:"Woher kommst du?", es:"¿De dónde vienes?", nota:"W-Frage: palabra interrogativa (pos. 1) + verbo (pos. 2).", n:1},
  {sol:"Wo wohnst du?", es:"¿Dónde vives?", nota:"W-Frage. Recuerda: <b>wo</b> = dónde, <b>wer</b> = quién.", n:1},
  {sol:"Warum lernst du Deutsch?", es:"¿Por qué aprendes alemán?", nota:"W-Frage con el verbo en 2ª posición.", n:1},
  {sol:"Mein Bruder spielt gern Fußball.", es:"A mi hermano le gusta jugar fútbol.", nota:"<i>Mein Bruder</i> son dos palabras pero UNA sola posición.", n:1},
  {sol:"Ich habe einen Bruder.", es:"Tengo un hermano.", nota:"Akkusativ masculino: ein → <b>einen</b>.", n:1},
  {sol:"Das ist für dich.", es:"Esto es para ti.", nota:"<b>für</b> es preposición de acusativo (DOGFU) → <i>für dich</i>, nunca <i>für du</i>.", n:1},
  {sol:"Ich trinke Kaffee ohne Zucker.", es:"Tomo café sin azúcar.", nota:"<b>ohne</b> → acusativo (DOGFU).", n:2},
  {sol:"Wir gehen durch den Park.", es:"Vamos por el parque.", nota:"<b>durch</b> + acusativo → der Park se vuelve <b>den</b> Park.", n:2},
  {sol:"Ich verstehe dich nicht.", es:"No te entiendo.", nota:"Negación total → <b>nicht</b> al final, detrás del objeto.", n:2},
  {sol:"Wir kaufen das Auto nicht.", es:"No compramos el auto.", nota:"Artículo definido → nicht (no kein), y va al final.", n:2},
  {sol:"Das ist kein Problem.", es:"No es ningún problema.", nota:"Sustantivo que iría con <i>ein</i> → <b>kein</b>.", n:2},
  {sol:"Sie hat keine Zeit.", es:"Ella no tiene tiempo.", nota:"Sustantivo sin artículo → <b>kein</b> (aquí femenino: keine).", n:2},
  {sol:"Ich kann gut Deutsch sprechen.", es:"Sé hablar bien alemán.", nota:"Paréntesis verbal: modal en 2ª posición, <b>infinitivo al final</b>.", n:2},
  {sol:"Morgen muss ich früh aufstehen.", alt:["Ich muss morgen früh aufstehen."], es:"Mañana tengo que levantarme temprano.", nota:"Con modal, el separable va entero al final: <i>aufstehen</i>.", n:2},
  {sol:"Kannst du mir helfen?", es:"¿Puedes ayudarme?", nota:"Pregunta sí/no: verbo en posición 1. <i>helfen</i> rige DATIVO → <b>mir</b>.", n:2},
  {sol:"Hier darf man nicht rauchen.", es:"Aquí no se puede fumar.", nota:"Prohibición = <b>nicht dürfen</b> (nunca <i>nicht müssen</i>).", n:3},
  {sol:"Ich stehe um sieben Uhr auf.", es:"Me levanto a las siete.", nota:"Separable en presente: el prefijo <b>auf</b> se va al final.", n:2},
  {sol:"Der Zug kommt um zehn Uhr an.", es:"El tren llega a las diez.", nota:"Separable: <i>ankommen</i> → <i>kommt … an</i>.", n:2},
  {sol:"Ich habe Deutsch gelernt.", es:"He aprendido alemán.", nota:"Perfekt: auxiliar en 2ª posición, <b>Partizip II al final</b>.", n:2},
  {sol:"Gestern habe ich viel gearbeitet.", alt:["Ich habe gestern viel gearbeitet."], es:"Ayer trabajé mucho.", nota:"Perfekt + inversión. <i>arbeiten</i> → gearbeitet (raíz en -t → -et).", n:3},
  {sol:"Ich bin nach Berlin gefahren.", es:"Fui a Berlín.", nota:"Movimiento A→B → auxiliar <b>sein</b>, no haben.", n:3},
  {sol:"Wir haben unsere Freunde besucht.", es:"Visitamos a nuestros amigos.", nota:"<i>besuchen</i> es inseparable → participio <b>sin</b> ge-.", n:3},
  {sol:"Ich bin um sieben Uhr aufgestanden.", es:"Me levanté a las siete.", nota:"Separable en Perfekt: el <b>ge-</b> va en medio → auf<b>ge</b>standen. Cambio de estado → sein.", n:3},
  {sol:"Nach der Arbeit gehe ich zum Arzt.", es:"Después del trabajo voy al médico.", nota:"<b>nach</b> y <b>zu</b> rigen dativo. zu+dem = <b>zum</b>.", n:3},
  {sol:"Ich fahre heute mit dem Bus nach Hause.", es:"Hoy voy a casa en bus.", nota:"TeKaMoLo: <b>Te</b>mporal (heute) → <b>Mo</b>dal (mit dem Bus) → <b>Lo</b>kal (nach Hause, al final).", n:3},
  {sol:"Er fliegt morgen wegen der Arbeit nach Berlin.", es:"Mañana vuela a Berlín por el trabajo.", nota:"TeKaMoLo completo: morgen (Te) → wegen der Arbeit (Ka) → nach Berlin (Lo).", n:3},
  {sol:"Ich lerne seit einem Jahr Deutsch.", es:"Aprendo alemán desde hace un año.", nota:"<b>seit</b> + dativo → ein → <b>einem</b>.", n:3},
  {sol:"Ich gebe dem Mann das Buch.", es:"Le doy el libro al hombre.", nota:"Con dos sustantivos, el <b>Dativo va primero</b>: dem Mann (a quién) antes que das Buch (qué).", n:3}
],

/* ---------- GRAMÁTICA (opción múltiple) ---------- */
gramatica: [
  /* Akkusativ */
  {q:"Ich habe ___ Bruder.", ops:["einen","ein","eine","einem"], ok:0, tema:"Akkusativ", nota:"<i>der Bruder</i> es masculino y aquí es objeto directo → ein se convierte en <b>einen</b>. Es el error nº1 de los principiantes.", n:1},
  {q:"Ich sehe ___ Hund. <small>(der Hund, definido)</small>", ops:["den","der","dem","das"], ok:0, tema:"Akkusativ", nota:"En acusativo <b>solo cambia el masculino</b>: der → <b>den</b>.", n:1},
  {q:"Ich sehe ___ Katze. <small>(die Katze, definido)</small>", ops:["die","den","der","das"], ok:0, tema:"Akkusativ", nota:"El femenino NO cambia en acusativo: die → die.", n:1},
  {q:"Ich kaufe ___ Buch. <small>(das Buch, definido)</small>", ops:["das","den","dem","die"], ok:0, tema:"Akkusativ", nota:"El neutro NO cambia en acusativo.", n:1},
  {q:"Sie braucht ___ Lampe. <small>(die Lampe, indefinido)</small>", ops:["eine","einen","ein","einer"], ok:0, tema:"Akkusativ", nota:"Femenino indefinido: <b>eine</b>, igual en nominativo y acusativo.", n:1},
  {q:"Ich brauche ___ Laptop. <small>(der Laptop, 'mi')</small>", ops:["meinen","mein","meine","meinem"], ok:0, tema:"Akkusativ", nota:"Los posesivos siguen a <i>ein</i>: masculino acusativo → <b>meinen</b>.", n:2},
  {q:"Verstehst du ___? <small>(a mí)</small>", ops:["mich","mir","ich","mein"], ok:0, tema:"Akkusativ", nota:"Pronombre de acusativo de <i>ich</i> → <b>mich</b>.", n:1},
  {q:"Kennst du ___? <small>(a él)</small>", ops:["ihn","ihm","er","sein"], ok:0, tema:"Akkusativ", nota:"Acusativo de <i>er</i> → <b>ihn</b> (como el inglés he → him).", n:2},
  {q:"Er ist ___ guter Lehrer.", ops:["ein","einen","einem","eines"], ok:0, tema:"Akkusativ", nota:"<b>sein</b> NO lleva acusativo, lleva nominativo. Lo mismo <i>werden</i> y <i>bleiben</i>.", n:3},
  {q:"¿Cuáles son las 5 preposiciones que SIEMPRE piden acusativo?", ops:["durch, ohne, gegen, für, um","aus, bei, mit, nach, seit","in, an, auf, über, unter","von, zu, seit, bei, mit"], ok:0, tema:"Akkusativ", nota:"El truco <b>DOGFU</b>: Durch, Ohne, Gegen, Für, Um.", n:2},
  {q:"Wir sitzen ___ den Tisch.", ops:["um","zu","mit","bei"], ok:0, tema:"Akkusativ", nota:"<b>um</b> (alrededor de) es de acusativo → den Tisch.", n:2},

  /* Dativ */
  {q:"Ich helfe ___ Mann.", ops:["dem","den","der","das"], ok:0, tema:"Dativ", nota:"<i>helfen</i> rige DATIVO. Masculino dativo: der → <b>dem</b>. Truco m-r-m-n.", n:2},
  {q:"Das Buch gehört ___ Frau.", ops:["der","die","dem","den"], ok:0, tema:"Dativ", nota:"Femenino en dativo: die → <b>der</b>. (Sí, confunde: parece masculino.)", n:2},
  {q:"Wir danken ___ Kind.", ops:["dem","das","der","den"], ok:0, tema:"Dativ", nota:"Neutro en dativo: das → <b>dem</b>.", n:2},
  {q:"Sie spielt mit den ___.", ops:["Kindern","Kinder","Kind","Kindes"], ok:0, tema:"Dativ", nota:"En dativo plural el sustantivo también añade <b>-n</b>: die Kinder → den Kind<b>ern</b>.", n:3},
  {q:"Kannst du ___ helfen? <small>(a mí)</small>", ops:["mir","mich","ich","mein"], ok:0, tema:"Dativ", nota:"Dativo de <i>ich</i> → <b>mir</b>. Acusativo sería <i>mich</i>.", n:2},
  {q:"Der Film gefällt ___. <small>(a ella)</small>", ops:["ihr","sie","ihn","ihm"], ok:0, tema:"Dativ", nota:"Dativo de <i>sie</i> (ella) → <b>ihr</b>. <i>gefallen</i> funciona como 'gustar'.", n:3},
  {q:"Wie geht es ___? <small>(a usted)</small>", ops:["Ihnen","Sie","Ihr","Ihm"], ok:0, tema:"Dativ", nota:"Dativo formal → <b>Ihnen</b>, con mayúscula.", n:2},
  {q:"¿Cuáles son las 7 preposiciones que SIEMPRE piden dativo?", ops:["aus, bei, mit, nach, seit, von, zu","durch, ohne, gegen, für, um","in, an, auf, vor, hinter","für, mit, ohne, seit, zu"], ok:0, tema:"Dativ", nota:"Mantra: <i>aus, bei, mit, nach, seit, von, zu — siempre dativo, y punto</i>.", n:2},
  {q:"Ich fahre ___ dem Bus.", ops:["mit","für","durch","ohne"], ok:0, tema:"Dativ", nota:"<b>mit</b> + dativo. <i>mit dem Bus</i> = en autobús.", n:1},
  {q:"zu + dem se contrae en…", ops:["zum","zur","zud","zom"], ok:0, tema:"Dativ", nota:"zu+dem = <b>zum</b> · zu+der = <b>zur</b> · bei+dem = <b>beim</b> · von+dem = <b>vom</b>.", n:2},
  {q:"Ich bin ___ Schule. <small>(estoy EN la escuela — Wo?)</small>", ops:["in der","in die","in den","in dem"], ok:0, tema:"Dativ", nota:"Wechselpräposition: <b>Wo?</b> (posición) → dativo → <i>in der Schule</i>.", n:3},
  {q:"Ich gehe ___ Schule. <small>(voy A la escuela — Wohin?)</small>", ops:["in die","in der","in dem","in den"], ok:0, tema:"Dativ", nota:"Wechselpräposition: <b>Wohin?</b> (movimiento con destino) → acusativo → <i>in die Schule</i>.", n:3},
  {q:"¿Cuál de estos verbos rige DATIVO?", ops:["helfen","kaufen","sehen","brauchen"], ok:0, tema:"Dativ", nota:"Rigen dativo: helfen, danken, gefallen, gehören, schmecken, antworten, passen.", n:2},

  /* nicht / kein */
  {q:"Ich habe ___ Zeit.", ops:["keine","nicht","kein","keinen"], ok:0, tema:"Negación", nota:"<i>die Zeit</i> sin artículo → <b>kein</b>, y en femenino <b>keine</b>.", n:1},
  {q:"Er arbeitet heute ___.", ops:["nicht","kein","keine","keinen"], ok:0, tema:"Negación", nota:"Se niega el verbo → <b>nicht</b>, y en negación total va al final.", n:1},
  {q:"Das ist ___ mein Buch.", ops:["nicht","kein","keine","keinen"], ok:0, tema:"Negación", nota:"Con posesivo → <b>nicht</b>, y va justo delante del elemento negado.", n:2},
  {q:"Wir haben ___ Auto.", ops:["kein","nicht","keine","keinen"], ok:0, tema:"Negación", nota:"<i>das Auto</i> con <i>ein</i> → <b>kein</b> (neutro).", n:1},
  {q:"Sie trinkt ___ Kaffee.", ops:["keinen","kein","keine","nicht"], ok:0, tema:"Negación", nota:"<i>der Kaffee</i> sin artículo y como objeto directo → <b>keinen</b> (masculino acusativo).", n:3},
  {q:"Ich habe ___ Brüder.", ops:["keine","kein","nicht","keinen"], ok:0, tema:"Negación", nota:"Plural → <b>keine</b>. Nunca <i>nicht Brüder</i>.", n:2},
  {q:"Ich kenne den Lehrer ___.", ops:["nicht","kein","keine","keinen"], ok:0, tema:"Negación", nota:"Artículo definido → <b>nicht</b>, y siempre <b>detrás</b> del objeto directo.", n:2},
  {q:"— Sprichst du kein Deutsch? — ¡Sí que hablo! →", ops:["Doch!","Ja!","Nein!","Nicht!"], ok:0, tema:"Negación", nota:"Para contradecir una pregunta negativa se usa <b>doch</b>, no <i>ja</i>. El inglés no tiene esta palabra.", n:3},

  /* modales y orden */
  {q:"¿Dónde va el infinitivo cuando hay un verbo modal?", ops:["Al final de la frase","Justo detrás del modal","En 2ª posición","Antes del sujeto"], ok:0, tema:"Modales", nota:"Paréntesis verbal (<i>Satzklammer</i>): modal en 2ª posición, <b>infinitivo al final de todo</b>.", n:1},
  {q:"Du ___ nicht kommen. <small>(está PROHIBIDO que vengas)</small>", ops:["darfst","musst","kannst","willst"], ok:0, tema:"Modales", nota:"Prohibición = <b>nicht dürfen</b>. <i>Du musst nicht kommen</i> significa 'no hace falta que vengas'.", n:3},
  {q:"<i>Ich will nach Berlin</i> significa…", ops:["Quiero ir a Berlín","Iré a Berlín","Debo ir a Berlín","Puedo ir a Berlín"], ok:0, tema:"Modales", nota:"Falso amigo brutal: <b>wollen = querer</b>, no tiene nada que ver con el futuro inglés <i>will</i>.", n:2},
  {q:"Para pedir algo educadamente en un café se usa…", ops:["Ich möchte…","Ich will…","Ich muss…","Ich soll…"], ok:0, tema:"Modales", nota:"<b>möchten</b> es el <i>wollen</i> educado, como el inglés <i>I'd like</i>.", n:1},
  {q:"En una frase principal alemana, el verbo conjugado va…", ops:["siempre en 2ª posición","siempre al final","siempre al principio","donde quieras"], ok:0, tema:"Orden", nota:"La regla de oro. Si algo distinto al sujeto ocupa el puesto 1 → <b>inversión</b>.", n:1},
  {q:"El orden de los complementos en alemán es…", ops:["Temporal → Kausal → Modal → Lokal","Lokal → Modal → Temporal","Modal → Temporal → Lokal","Kausal → Lokal → Temporal"], ok:0, tema:"Orden", nota:"<b>TeKaMoLo</b>. El lugar siempre al final — justo al revés del español.", n:2},
  {q:"En una pregunta de sí/no, el verbo va…", ops:["en 1ª posición","en 2ª posición","al final","con el auxiliar 'do'"], ok:0, tema:"Orden", nota:"<i>Wohnst du in Berlin?</i> El alemán NO tiene el auxiliar <i>do</i> del inglés.", n:1},

  /* Perfekt */
  {q:"Ich ___ nach Hause gegangen.", ops:["bin","habe","hat","ist"], ok:0, tema:"Perfekt", nota:"Movimiento de A a B → auxiliar <b>sein</b>. ❌ <i>Ich habe gegangen</i>.", n:2},
  {q:"Wir ___ Pizza gegessen.", ops:["haben","sind","seid","ist"], ok:0, tema:"Perfekt", nota:"El 90% de los verbos usan <b>haben</b>. <i>essen</i> es uno de ellos.", n:1},
  {q:"Sie ___ zu Hause geblieben.", ops:["ist","hat","haben","sind"], ok:0, tema:"Perfekt", nota:"<i>bleiben</i> es excepción fija: aunque no hay movimiento, lleva <b>sein</b>.", n:3},
  {q:"El Partizip II de <i>studieren</i> es…", ops:["studiert","gestudiert","gestudierte","studieren"], ok:0, tema:"Perfekt", nota:"Los verbos en <b>-ieren</b> nunca llevan <i>ge-</i>.", n:2},
  {q:"El Partizip II de <i>besuchen</i> es…", ops:["besucht","gebesucht","besuchen","bebesucht"], ok:0, tema:"Perfekt", nota:"Prefijo <b>inseparable</b> (be-) → sin <i>ge-</i>.", n:2},
  {q:"El Partizip II de <i>aufstehen</i> es…", ops:["aufgestanden","geaufstanden","aufstanden","gestandenauf"], ok:0, tema:"Perfekt", nota:"Separable: el <b>ge- va en medio</b>, entre prefijo y raíz.", n:3},
  {q:"¿Dónde va <i>nicht</i> en el Perfekt?", ops:["justo antes del participio","después del participio","en 2ª posición","antes del auxiliar"], ok:0, tema:"Perfekt", nota:"<i>Ich habe das <b>nicht</b> gemacht.</i> Nunca después del participio.", n:3},

  /* separables */
  {q:"En presente, el prefijo de un verbo separable va…", ops:["al final de la frase","pegado al verbo","antes del sujeto","en 2ª posición"], ok:0, tema:"Separables", nota:"<i>Ich stehe um 7 Uhr <b>auf</b>.</i> ❌ <i>Ich aufstehe…</i>", n:1},
  {q:"¿Cuál es el truco infalible para saber si un prefijo es separable?", ops:["El acento tónico cae en el prefijo","Empieza por vocal","Tiene más de 3 letras","Termina en consonante"], ok:0, tema:"Separables", nota:"<b>AUF</b>stehen (separable) vs be<b>SU</b>chen (inseparable). Funciona el 100% de las veces.", n:3},
  {q:"¿Cuáles son los prefijos SIEMPRE inseparables?", ops:["be-, ver-, er-, ent-, ge-, zer-","auf-, ein-, an-, mit-","ab-, zurück-, weg-, fern-","vor-, aus-, zu-, nach-"], ok:0, tema:"Separables", nota:"Y nunca llevan <i>ge-</i> en el participio.", n:3},
  {q:"Con un verbo modal, el separable…", ops:["va entero en infinitivo al final","se parte igual","pierde el prefijo","va al principio"], ok:0, tema:"Separables", nota:"Regla mental: <b>conjugado → se parte; infinitivo → entero</b>. <i>Ich muss früh aufstehen.</i>", n:2},

  /* pronunciación y básicos */
  {q:"En alemán, la <b>w</b> se pronuncia…", ops:["como 'v'","como 'u'","como 'w' inglesa","como 'b'"], ok:0, tema:"Pronunciación", nota:"<i>Wasser</i> = 'váser'. Y la <b>v</b> se pronuncia 'f': <i>Vater</i> = 'fáter'.", n:1},
  {q:"El grupo <b>ei</b> se pronuncia…", ops:["'ái'","'éi'","'íi'","'ói'"], ok:0, tema:"Pronunciación", nota:"<i>nein</i> = 'náin'. Y <b>ie</b> se pronuncia 'íi': <i>sieben</i> = 'síben'.", n:1},
  {q:"El grupo <b>eu</b> se pronuncia…", ops:["'ói'","'éu'","'ái'","'úe'"], ok:0, tema:"Pronunciación", nota:"<i>Deutsch</i> = 'dóitch', <i>heute</i> = 'hóite'.", n:2},
  {q:"La <b>z</b> alemana suena…", ops:["'ts'","'z' zumbada","'s'","'d'"], ok:0, tema:"Pronunciación", nota:"<i>Zeit</i> = 'tsáit'.", n:1},
  {q:"En plural, los tres géneros usan el artículo…", ops:["die","der","das","den"], ok:0, tema:"Artículos", nota:"Buena noticia: en plural todo se fusiona en <b>die</b>.", n:1},
  {q:"¿Cómo se dice 'tengo 25 años'?", ops:["Ich bin 25 Jahre alt.","Ich habe 25 Jahre.","Ich habe 25 Jahre alt.","Ich bin 25 Jahre."], ok:0, tema:"Errores clásicos", nota:"Con <b>sein</b>, como en inglés (<i>I am 25</i>). El error nº1 del hispanohablante.", n:1},
  {q:"¿Cómo se dice 'soy profesor'?", ops:["Ich bin Lehrer.","Ich bin ein Lehrer.","Ich habe Lehrer.","Ich bin der Lehrer."], ok:0, tema:"Errores clásicos", nota:"Las profesiones van <b>sin artículo</b>. Aquí el español manda y el inglés te confundiría.", n:1},
  {q:"<i>studieren</i> vs <i>lernen</i>: ¿cuál usas para 'estudiar para un examen'?", ops:["lernen","studieren","beide","keins"], ok:0, tema:"Errores clásicos", nota:"<b>studieren</b> = cursar una carrera. <b>lernen</b> = estudiar/aprender. <i>Ich lerne für die Prüfung.</i>", n:3},
  {q:"Si no sabes si tutear o no a alguien, usa…", ops:["Sie","du","ihr","es"], ok:0, tema:"Errores clásicos", nota:"Pasarse de formal nunca ofende; tutear a quien no debes, sí.", n:1}
]

};
