/* ============================================================
   DATOS · ÁRABE FUSHA
   Extraído de las Lecciones 01–18 de Idiomas/Arabe
   n = nivel: 1 fácil · 2 intermedio · 3 difícil
   ============================================================ */

window.ARABE = {

/* ---------- LAS 28 LETRAS ---------- */
letras: [
  {ch:"ا", nombre:"alif",  son:"ā",  desc:"palito vertical; soporte y 'a' larga", fam:"rebeldes",   ini:"ا", med:"ـا", fin:"ـا", conecta:false, solar:false, n:1},
  {ch:"ب", nombre:"bāʼ",   son:"b",  desc:"como la b de 'bota'",                  fam:"barquita",   ini:"بـ", med:"ـبـ", fin:"ـب", conecta:true,  solar:false, n:1},
  {ch:"ت", nombre:"tāʼ",   son:"t",  desc:"como la t de 'taza'",                  fam:"barquita",   ini:"تـ", med:"ـتـ", fin:"ـت", conecta:true,  solar:true,  n:1},
  {ch:"ث", nombre:"thāʼ",  son:"th", desc:"th inglesa de 'think' / z de España",  fam:"barquita",   ini:"ثـ", med:"ـثـ", fin:"ـث", conecta:true,  solar:true,  n:1},
  {ch:"ج", nombre:"jīm",   son:"j",  desc:"j inglesa de 'jam'",                   fam:"barriga",    ini:"جـ", med:"ـجـ", fin:"ـج", conecta:true,  solar:false, n:1},
  {ch:"ح", nombre:"ḥāʼ",   son:"ḥ",  desc:"H fuerte con aire, SIN raspar",        fam:"barriga",    ini:"حـ", med:"ـحـ", fin:"ـح", conecta:true,  solar:false, n:2},
  {ch:"خ", nombre:"khāʼ",  son:"kh", desc:"la jota española de 'jamón'",          fam:"barriga",    ini:"خـ", med:"ـخـ", fin:"ـخ", conecta:true,  solar:false, n:1},
  {ch:"د", nombre:"dāl",   son:"d",  desc:"como la d de 'dedo'",                  fam:"rebeldes",   ini:"د", med:"ـد", fin:"ـد", conecta:false, solar:true,  n:1},
  {ch:"ذ", nombre:"dhāl",  son:"dh", desc:"th inglesa de 'this' (con voz)",       fam:"rebeldes",   ini:"ذ", med:"ـذ", fin:"ـذ", conecta:false, solar:true,  n:2},
  {ch:"ر", nombre:"rāʼ",   son:"r",  desc:"r suave de 'pero'",                    fam:"rebeldes",   ini:"ر", med:"ـر", fin:"ـر", conecta:false, solar:true,  n:1},
  {ch:"ز", nombre:"zāy",   son:"z",  desc:"z zumbada, como la z inglesa de 'zoo'",fam:"rebeldes",   ini:"ز", med:"ـز", fin:"ـز", conecta:false, solar:true,  n:2},
  {ch:"س", nombre:"sīn",   son:"s",  desc:"s normal de 'sol'",                    fam:"silbantes",  ini:"سـ", med:"ـسـ", fin:"ـس", conecta:true,  solar:true,  n:1},
  {ch:"ش", nombre:"shīn",  son:"sh", desc:"sh inglesa de 'show'",                 fam:"silbantes",  ini:"شـ", med:"ـشـ", fin:"ـش", conecta:true,  solar:true,  n:1},
  {ch:"ص", nombre:"ṣād",   son:"ṣ",  desc:"s ENFÁTICA: gruesa y grave",           fam:"silbantes",  ini:"صـ", med:"ـصـ", fin:"ـص", conecta:true,  solar:true,  n:2},
  {ch:"ض", nombre:"ḍād",   son:"ḍ",  desc:"d ENFÁTICA: gruesa y grave",           fam:"silbantes",  ini:"ضـ", med:"ـضـ", fin:"ـض", conecta:true,  solar:true,  n:3},
  {ch:"ط", nombre:"ṭāʼ",   son:"ṭ",  desc:"t ENFÁTICA: gruesa y grave",           fam:"enfáticas",  ini:"طـ", med:"ـطـ", fin:"ـط", conecta:true,  solar:true,  n:2},
  {ch:"ظ", nombre:"ẓāʼ",   son:"ẓ",  desc:"th/z ENFÁTICA: gruesa y grave",        fam:"enfáticas",  ini:"ظـ", med:"ـظـ", fin:"ـظ", conecta:true,  solar:true,  n:3},
  {ch:"ع", nombre:"ʿayn",  son:"ʿ",  desc:"sonido profundo de garganta, con voz", fam:"guturales",  ini:"عـ", med:"ـعـ", fin:"ـع", conecta:true,  solar:false, n:3},
  {ch:"غ", nombre:"ghayn", son:"gh", desc:"como hacer gárgaras; r francesa",      fam:"guturales",  ini:"غـ", med:"ـغـ", fin:"ـغ", conecta:true,  solar:false, n:3},
  {ch:"ف", nombre:"fāʼ",   son:"f",  desc:"como la f de 'foca'",                  fam:"círculo",    ini:"فـ", med:"ـفـ", fin:"ـف", conecta:true,  solar:false, n:1},
  {ch:"ق", nombre:"qāf",   son:"q",  desc:"k PROFUNDA, desde el fondo de la garganta", fam:"círculo", ini:"قـ", med:"ـقـ", fin:"ـق", conecta:true, solar:false, n:2},
  {ch:"ك", nombre:"kāf",   son:"k",  desc:"como la k de 'kilo'",                  fam:"círculo",    ini:"كـ", med:"ـكـ", fin:"ـك", conecta:true,  solar:false, n:1},
  {ch:"ل", nombre:"lām",   son:"l",  desc:"como la l de 'luna'",                  fam:"círculo",    ini:"لـ", med:"ـلـ", fin:"ـل", conecta:true,  solar:true,  n:1},
  {ch:"م", nombre:"mīm",   son:"m",  desc:"como la m de 'mano'",                  fam:"finales",    ini:"مـ", med:"ـمـ", fin:"ـم", conecta:true,  solar:false, n:1},
  {ch:"ن", nombre:"nūn",   son:"n",  desc:"como la n de 'nube'",                  fam:"finales",    ini:"نـ", med:"ـنـ", fin:"ـن", conecta:true,  solar:true,  n:1},
  {ch:"ه", nombre:"hāʼ",   son:"h",  desc:"h aspirada suave, como la h inglesa",  fam:"finales",    ini:"هـ", med:"ـهـ", fin:"ـه", conecta:true,  solar:false, n:2},
  {ch:"و", nombre:"wāw",   son:"w",  desc:"w de 'web'; también 'u' larga",        fam:"rebeldes",   ini:"و", med:"ـو", fin:"ـو", conecta:false, solar:false, n:1},
  {ch:"ي", nombre:"yāʼ",   son:"y",  desc:"y de 'yo'; también 'i' larga",         fam:"finales",    ini:"يـ", med:"ـيـ", fin:"ـي", conecta:true,  solar:false, n:1}
],

hamza: {ch:"ء", nombre:"hamza", son:"ʼ", desc:"golpe glotal, el cortecito de 'uh-oh'"},

/* ---------- MARCAS DIACRÍTICAS ---------- */
marcas: [
  {ch:"بَ", nombre:"fatha",  son:"a", desc:"rayita ARRIBA → vocal corta 'a'", n:1},
  {ch:"بِ", nombre:"kasra",  son:"i", desc:"rayita ABAJO → vocal corta 'i'. La única que va abajo", n:1},
  {ch:"بُ", nombre:"damma",  son:"u", desc:"ganchito ARRIBA → vocal corta 'u'", n:1},
  {ch:"بْ", nombre:"sukun",  son:"—", desc:"circulito → la consonante NO lleva vocal", n:1},
  {ch:"بّ", nombre:"shadda", son:"bb",desc:"'w' pequeña → consonante DOBLE. ¡Cambia el significado!", n:2},
  {ch:"بًا",nombre:"tanwin -an", son:"-an", desc:"doble fatha (+alif) → terminación indefinida -an", n:2},
  {ch:"بٍ", nombre:"tanwin -in", son:"-in", desc:"doble kasra → terminación indefinida -in", n:3},
  {ch:"بٌ", nombre:"tanwin -un", son:"-un", desc:"doble damma → terminación indefinida -un", n:2},
  {ch:"ة",  nombre:"ta marbuta",son:"-a", desc:"la ه con los puntos de la ت: marca de FEMENINO, solo al final", n:2}
],

/* ---------- VOCABULARIO ---------- */
vocab: [
  /* saludos y cortesía */
  {ar:"مَرْحَبًا", tr:"marḥaban", es:"hola", cat:"saludos", n:1},
  {ar:"أَهْلًا", tr:"ahlan", es:"hola / bienvenido", cat:"saludos", n:1},
  {ar:"صَبَاح", tr:"ṣabāḥ", es:"mañana", cat:"saludos", n:1},
  {ar:"مَسَاء", tr:"masāʼ", es:"tarde / noche", cat:"saludos", n:2},
  {ar:"خَيْر", tr:"khayr", es:"bien, bondad", cat:"saludos", n:2},
  {ar:"نَعَمْ", tr:"naʿam", es:"sí", cat:"saludos", n:1},
  {ar:"لَا", tr:"lā", es:"no", cat:"saludos", n:1},
  {ar:"شُكْرًا", tr:"shukran", es:"gracias", cat:"saludos", n:1},
  {ar:"عَفْوًا", tr:"ʿafwan", es:"de nada / perdón", cat:"saludos", n:2},
  {ar:"سَلَام", tr:"salām", es:"paz", cat:"saludos", n:1},
  {ar:"حَال", tr:"ḥāl", es:"estado, situación", cat:"saludos", n:2},
  /* personas y familia */
  {ar:"رَجُل", tr:"rajul", es:"hombre", cat:"personas", gen:"m", n:1},
  {ar:"اِمْرَأَة", tr:"imraʼa", es:"mujer", cat:"personas", gen:"f", n:2},
  {ar:"وَلَد", tr:"walad", es:"niño, chico", cat:"personas", gen:"m", n:1},
  {ar:"بِنْت", tr:"bint", es:"niña, hija", cat:"personas", gen:"f", n:1},
  {ar:"أَب", tr:"ab", es:"padre", cat:"personas", gen:"m", n:1},
  {ar:"أُمّ", tr:"umm", es:"madre", cat:"personas", gen:"f", n:1},
  {ar:"اِبْن", tr:"ibn", es:"hijo", cat:"personas", gen:"m", n:2},
  {ar:"أَخ", tr:"akh", es:"hermano", cat:"personas", gen:"m", n:1},
  {ar:"أُخْت", tr:"ukht", es:"hermana", cat:"personas", gen:"f", n:1},
  {ar:"جَدّ", tr:"jadd", es:"abuelo", cat:"personas", gen:"m", n:2},
  {ar:"جَدَّة", tr:"jadda", es:"abuela", cat:"personas", gen:"f", n:2},
  {ar:"صَدِيق", tr:"ṣadīq", es:"amigo", cat:"personas", gen:"m", n:1},
  {ar:"صَدِيقَة", tr:"ṣadīqa", es:"amiga", cat:"personas", gen:"f", n:1},
  {ar:"مُدَرِّس", tr:"mudarris", es:"profesor", cat:"personas", gen:"m", n:1},
  {ar:"مُدَرِّسَة", tr:"mudarrisa", es:"profesora", cat:"personas", gen:"f", n:2},
  {ar:"طَالِب", tr:"ṭālib", es:"estudiante", cat:"personas", gen:"m", n:1},
  {ar:"طَبِيب", tr:"ṭabīb", es:"médico", cat:"personas", gen:"m", n:1},
  /* casa y objetos */
  {ar:"بَيْت", tr:"bayt", es:"casa", cat:"objetos", gen:"m", n:1},
  {ar:"بَاب", tr:"bāb", es:"puerta", cat:"objetos", gen:"m", n:1},
  {ar:"نَافِذَة", tr:"nāfidha", es:"ventana", cat:"objetos", gen:"f", n:2},
  {ar:"غُرْفَة", tr:"ghurfa", es:"habitación", cat:"objetos", gen:"f", n:2},
  {ar:"كُرْسِيّ", tr:"kursī", es:"silla", cat:"objetos", gen:"m", n:2},
  {ar:"طَاوِلَة", tr:"ṭāwila", es:"mesa", cat:"objetos", gen:"f", n:2},
  {ar:"سَرِير", tr:"sarīr", es:"cama", cat:"objetos", gen:"m", n:2},
  {ar:"كِتَاب", tr:"kitāb", es:"libro", cat:"objetos", gen:"m", n:1},
  {ar:"قَلَم", tr:"qalam", es:"lápiz, bolígrafo", cat:"objetos", gen:"m", n:1},
  {ar:"مِفْتَاح", tr:"miftāḥ", es:"llave", cat:"objetos", gen:"m", n:2},
  {ar:"سَاعَة", tr:"sāʿa", es:"reloj / hora", cat:"objetos", gen:"f", n:2},
  {ar:"هَاتِف", tr:"hātif", es:"teléfono", cat:"objetos", gen:"m", n:2},
  {ar:"سَيَّارَة", tr:"sayyāra", es:"auto", cat:"objetos", gen:"f", n:2},
  {ar:"رِسَالَة", tr:"risāla", es:"carta", cat:"objetos", gen:"f", n:3},
  /* comida */
  {ar:"مَاء", tr:"māʼ", es:"agua", cat:"comida", gen:"m", n:1},
  {ar:"خُبْز", tr:"khubz", es:"pan", cat:"comida", gen:"m", n:1},
  {ar:"لَحْم", tr:"laḥm", es:"carne", cat:"comida", gen:"m", n:2},
  {ar:"أَرُزّ", tr:"aruzz", es:"arroz", cat:"comida", gen:"m", n:3},
  {ar:"سَمَك", tr:"samak", es:"pescado", cat:"comida", gen:"m", n:2},
  {ar:"بَيْضَة", tr:"bayḍa", es:"huevo", cat:"comida", gen:"f", n:2},
  {ar:"حَلِيب", tr:"ḥalīb", es:"leche", cat:"comida", gen:"m", n:2},
  {ar:"جُبْن", tr:"jubn", es:"queso", cat:"comida", gen:"m", n:3},
  {ar:"شَاي", tr:"shāy", es:"té", cat:"comida", gen:"m", n:1},
  {ar:"قَهْوَة", tr:"qahwa", es:"café", cat:"comida", gen:"f", n:1},
  {ar:"سُكَّر", tr:"sukkar", es:"azúcar", cat:"comida", gen:"m", n:2},
  {ar:"تُفَّاح", tr:"tuffāḥ", es:"manzana", cat:"comida", gen:"m", n:2},
  /* lugares */
  {ar:"مَدْرَسَة", tr:"madrasa", es:"escuela", cat:"lugares", gen:"f", n:1},
  {ar:"جَامِعَة", tr:"jāmiʿa", es:"universidad", cat:"lugares", gen:"f", n:2},
  {ar:"سُوق", tr:"sūq", es:"mercado", cat:"lugares", gen:"m", n:1},
  {ar:"مَطْعَم", tr:"maṭʿam", es:"restaurante", cat:"lugares", gen:"m", n:2},
  {ar:"مُسْتَشْفَى", tr:"mustashfā", es:"hospital", cat:"lugares", gen:"m", n:3},
  {ar:"مَدِينَة", tr:"madīna", es:"ciudad", cat:"lugares", gen:"f", n:2},
  {ar:"قَرْيَة", tr:"qarya", es:"pueblo", cat:"lugares", gen:"f", n:3},
  {ar:"شَارِع", tr:"shāriʿ", es:"calle", cat:"lugares", gen:"m", n:2},
  {ar:"مَكْتَب", tr:"maktab", es:"oficina, escritorio", cat:"lugares", gen:"m", n:1},
  {ar:"مَكْتَبَة", tr:"maktaba", es:"biblioteca, librería", cat:"lugares", gen:"f", n:2},
  {ar:"بَلَد", tr:"balad", es:"país", cat:"lugares", gen:"m", n:2},
  {ar:"مَسْجِد", tr:"masjid", es:"mezquita", cat:"lugares", gen:"m", n:2},
  {ar:"مَطْبَخ", tr:"maṭbakh", es:"cocina", cat:"lugares", gen:"m", n:3},
  /* adjetivos y conectores */
  {ar:"كَبِير", tr:"kabīr", es:"grande", cat:"adjetivos", n:1},
  {ar:"صَغِير", tr:"ṣaghīr", es:"pequeño", cat:"adjetivos", n:1},
  {ar:"جَمِيل", tr:"jamīl", es:"bonito", cat:"adjetivos", n:1},
  {ar:"جَدِيد", tr:"jadīd", es:"nuevo", cat:"adjetivos", n:1},
  {ar:"قَدِيم", tr:"qadīm", es:"viejo, antiguo", cat:"adjetivos", n:2},
  {ar:"طَوِيل", tr:"ṭawīl", es:"largo, alto", cat:"adjetivos", n:2},
  {ar:"قَصِير", tr:"qaṣīr", es:"corto, bajo", cat:"adjetivos", n:2},
  {ar:"سَعِيد", tr:"saʿīd", es:"feliz", cat:"adjetivos", n:2},
  {ar:"مَرِيض", tr:"marīḍ", es:"enfermo", cat:"adjetivos", n:2},
  {ar:"بَعِيد", tr:"baʿīd", es:"lejano", cat:"adjetivos", n:3},
  {ar:"قَرِيب", tr:"qarīb", es:"cercano", cat:"adjetivos", n:3},
  {ar:"بَارِد", tr:"bārid", es:"frío", cat:"adjetivos", n:3},
  {ar:"هُنَا", tr:"hunā", es:"aquí", cat:"conectores", n:1},
  {ar:"هُنَاكَ", tr:"hunāka", es:"allí", cat:"conectores", n:2},
  {ar:"وَ", tr:"wa", es:"y", cat:"conectores", n:1},
  {ar:"فِي", tr:"fī", es:"en", cat:"conectores", n:1},
  {ar:"مِنْ", tr:"min", es:"de, desde", cat:"conectores", n:1},
  {ar:"عَلَى", tr:"ʿalā", es:"sobre, encima de", cat:"conectores", n:2},
  {ar:"مَعَ", tr:"maʿa", es:"con", cat:"conectores", n:2},
  {ar:"أَمْسِ", tr:"amsi", es:"ayer", cat:"conectores", n:3},
  {ar:"بَعْدَ", tr:"baʿda", es:"después de", cat:"conectores", n:3}
],

/* ---------- FRASES HECHAS ---------- */
frases: [
  {ar:"اَلسَّلَامُ عَلَيْكُمْ", tr:"as-salāmu ʿalaykum", es:"la paz sea contigo (saludo universal)", n:1},
  {ar:"وَعَلَيْكُمُ السَّلَام", tr:"wa-ʿalaykumu s-salām", es:"y contigo la paz (respuesta)", n:1},
  {ar:"صَبَاحُ الْخَيْرِ", tr:"ṣabāḥu l-khayr", es:"buenos días", n:1},
  {ar:"صَبَاحُ النُّورِ", tr:"ṣabāḥu n-nūr", es:"respuesta a 'buenos días'", n:2},
  {ar:"مَسَاءُ الْخَيْرِ", tr:"masāʼu l-khayr", es:"buenas tardes/noches", n:2},
  {ar:"كَيْفَ حَالُكَ؟", tr:"kayfa ḥāluka?", es:"¿cómo estás? (a un hombre)", n:2},
  {ar:"كَيْفَ حَالُكِ؟", tr:"kayfa ḥāluki?", es:"¿cómo estás? (a una mujer)", n:3},
  {ar:"بِخَيْرٍ، اَلْحَمْدُ لِلَّهِ", tr:"bi-khayrin, al-ḥamdu li-llāh", es:"bien, gracias a Dios", n:2},
  {ar:"مِنْ فَضْلِكَ", tr:"min faḍlika", es:"por favor (a un hombre)", n:2},
  {ar:"مِنْ فَضْلِكِ", tr:"min faḍliki", es:"por favor (a una mujer)", n:3},
  {ar:"إِنْ شَاءَ اللَّهُ", tr:"in shāʼa llāh", es:"si Dios quiere / ojalá", n:2},
  {ar:"مَا اسْمُكَ؟", tr:"mā smuka?", es:"¿cómo te llamas? (a un hombre)", n:2},
  {ar:"اِسْمِي…", tr:"ismī…", es:"me llamo…", n:1},
  {ar:"لَا أَفْهَمُ", tr:"lā afhamu", es:"no entiendo", n:2},
  {ar:"مَعَ السَّلَامَة", tr:"maʿa s-salāma", es:"adiós", n:1}
],

/* ---------- LECTURA VOCALIZADA ---------- */
lectura: [
  {ar:"مَنْ", tr:"man", es:"¿quién?", n:1},
  {ar:"مِنْ", tr:"min", es:"de / desde", n:1},
  {ar:"هُوَ", tr:"huwa", es:"él", n:1},
  {ar:"هِيَ", tr:"hiya", es:"ella", n:1},
  {ar:"كَتَبَ", tr:"kataba", es:"él escribió", n:1},
  {ar:"دَرْس", tr:"dars", es:"lección", n:1},
  {ar:"بَاب", tr:"bāb", es:"puerta", n:1},
  {ar:"كِتَاب", tr:"kitāb", es:"libro", n:1},
  {ar:"نُور", tr:"nūr", es:"luz", n:1},
  {ar:"فِيل", tr:"fīl", es:"elefante", n:2},
  {ar:"كَبِير", tr:"kabīr", es:"grande", n:1},
  {ar:"جَمِيل", tr:"jamīl", es:"bonito", n:2},
  {ar:"سَلَام", tr:"salām", es:"paz", n:1},
  {ar:"مُدَرِّس", tr:"mudarris", es:"profesor", n:2, nota:"la ر lleva shadda + kasra → 'rri'"},
  {ar:"كِتَابٌ", tr:"kitābun", es:"un libro", n:2, nota:"tanwin -un: indefinido"},
  {ar:"مَدْرَسَة", tr:"madrasa", es:"escuela", n:2},
  {ar:"شُكْرًا", tr:"shukran", es:"gracias", n:2, nota:"tanwin -an apoyado en alif"},
  {ar:"دَرَسَ", tr:"darasa", es:"él estudió", n:2},
  {ar:"دَرَّسَ", tr:"darrasa", es:"él enseñó", n:3, nota:"¡con shadda! La doble r cambia el significado"},
  {ar:"بِنْت", tr:"bint", es:"niña, hija", n:2, nota:"la ن lleva sukun: suena seca"},
  {ar:"سَيَّارَة", tr:"sayyāra", es:"auto", n:3, nota:"ي con shadda → 'yy'"},
  {ar:"مَكْتَبَة", tr:"maktaba", es:"biblioteca", n:2},
  {ar:"جَامِعَة", tr:"jāmiʿa", es:"universidad", n:3},
  {ar:"مُسْتَشْفَى", tr:"mustashfā", es:"hospital", n:3},
  {ar:"قَهْوَة", tr:"qahwa", es:"café", n:2},
  {ar:"تُفَّاح", tr:"tuffāḥ", es:"manzana", n:3, nota:"ف con shadda → 'ff'"},
  {ar:"عِشْرُونَ", tr:"ʿishrūna", es:"veinte", n:3},
  {ar:"أُخْت", tr:"ukht", es:"hermana", n:2},
  {ar:"غُرْفَة", tr:"ghurfa", es:"habitación", n:2},
  {ar:"كُرْسِيّ", tr:"kursī", es:"silla", n:3}
],

/* ---------- SOLARES Y LUNARES ---------- */
articulo: [
  {ar:"اَلْقَمَر", base:"قمر", tr:"al-qamar", es:"la luna", solar:false, ini:"ق", n:1},
  {ar:"اَلشَّمْس", base:"شمس", tr:"ash-shams", es:"el sol", solar:true, ini:"ش", n:1},
  {ar:"اَلْبَيْت", base:"بيت", tr:"al-bayt", es:"la casa", solar:false, ini:"ب", n:1},
  {ar:"اَلْكِتَاب", base:"كتاب", tr:"al-kitāb", es:"el libro", solar:false, ini:"ك", n:1},
  {ar:"اَلْوَلَد", base:"ولد", tr:"al-walad", es:"el niño", solar:false, ini:"و", n:1},
  {ar:"اَلْمَاء", base:"ماء", tr:"al-māʼ", es:"el agua", solar:false, ini:"م", n:1},
  {ar:"اَلْجَامِعَة", base:"جامعة", tr:"al-jāmiʿa", es:"la universidad", solar:false, ini:"ج", n:2},
  {ar:"اَلسَّلَام", base:"سلام", tr:"as-salām", es:"la paz", solar:true, ini:"س", n:1},
  {ar:"اَلنُّور", base:"نور", tr:"an-nūr", es:"la luz", solar:true, ini:"ن", n:1},
  {ar:"اَلطَّالِب", base:"طالب", tr:"aṭ-ṭālib", es:"el estudiante", solar:true, ini:"ط", n:2},
  {ar:"اَلرَّجُل", base:"رجل", tr:"ar-rajul", es:"el hombre", solar:true, ini:"ر", n:1},
  {ar:"اَلدَّرْس", base:"درس", tr:"ad-dars", es:"la lección", solar:true, ini:"د", n:1},
  {ar:"اَلتُّفَّاح", base:"تفاح", tr:"at-tuffāḥ", es:"la manzana", solar:true, ini:"ت", n:2},
  {ar:"اَلصَّدِيق", base:"صديق", tr:"aṣ-ṣadīq", es:"el amigo", solar:true, ini:"ص", n:2},
  {ar:"اَلْقَلَم", base:"قلم", tr:"al-qalam", es:"el lápiz", solar:false, ini:"ق", n:1},
  {ar:"اَلنَّافِذَة", base:"نافذة", tr:"an-nāfidha", es:"la ventana", solar:true, ini:"ن", n:2},
  {ar:"اَلْمَطْعَم", base:"مطعم", tr:"al-maṭʿam", es:"el restaurante", solar:false, ini:"م", n:2},
  {ar:"اَلسُّوق", base:"سوق", tr:"as-sūq", es:"el mercado", solar:true, ini:"س", n:1},
  {ar:"اَلْهَاتِف", base:"هاتف", tr:"al-hātif", es:"el teléfono", solar:false, ini:"ه", n:2},
  {ar:"اَلزَّهْرَة", base:"زهرة", tr:"az-zahra", es:"la flor", solar:true, ini:"ز", n:2},
  {ar:"اَلْعَرَبِيَّة", base:"عربية", tr:"al-ʿarabiyya", es:"el árabe (lengua)", solar:false, ini:"ع", n:2},
  {ar:"اَللُّغَة", base:"لغة", tr:"al-lugha", es:"la lengua", solar:true, ini:"ل", n:3, nota:"¡la ل también es solar!"},
  {ar:"اَلْبَاب", base:"باب", tr:"al-bāb", es:"la puerta", solar:false, ini:"ب", n:1},
  {ar:"اَلشَّاي", base:"شاي", tr:"ash-shāy", es:"el té", solar:true, ini:"ش", n:1},
  {ar:"اَلْكُرْسِيّ", base:"كرسي", tr:"al-kursī", es:"la silla", solar:false, ini:"ك", n:2},
  {ar:"اَلْغُرْفَة", base:"غرفة", tr:"al-ghurfa", es:"la habitación", solar:false, ini:"غ", n:2},
  {ar:"اَلثَّوْب", base:"ثوب", tr:"ath-thawb", es:"la ropa/túnica", solar:true, ini:"ث", n:3},
  {ar:"اَلذَّهَب", base:"ذهب", tr:"adh-dhahab", es:"el oro", solar:true, ini:"ذ", n:3},
  {ar:"اَلضَّيْف", base:"ضيف", tr:"aḍ-ḍayf", es:"el invitado", solar:true, ini:"ض", n:3},
  {ar:"اَلظُّهْر", base:"ظهر", tr:"aẓ-ẓuhr", es:"el mediodía", solar:true, ini:"ظ", n:3},
  {ar:"اَلْحَلِيب", base:"حليب", tr:"al-ḥalīb", es:"la leche", solar:false, ini:"ح", n:2},
  {ar:"اَلْخُبْز", base:"خبز", tr:"al-khubz", es:"el pan", solar:false, ini:"خ", n:2},
  {ar:"اَلْفِيل", base:"فيل", tr:"al-fīl", es:"el elefante", solar:false, ini:"ف", n:2},
  {ar:"اَلْيَد", base:"يد", tr:"al-yad", es:"la mano", solar:false, ini:"ي", n:2}
],

/* ---------- VERBOS EN PASADO ---------- */
pronombres: [
  {ar:"أَنَا", tr:"anā", es:"yo", suf:"ْتُ", trSuf:"-tu"},
  {ar:"أَنْتَ", tr:"anta", es:"tú (a un hombre)", suf:"ْتَ", trSuf:"-ta"},
  {ar:"أَنْتِ", tr:"anti", es:"tú (a una mujer)", suf:"ْتِ", trSuf:"-ti"},
  {ar:"هُوَ", tr:"huwa", es:"él", suf:"َ", trSuf:"-a"},
  {ar:"هِيَ", tr:"hiya", es:"ella", suf:"َتْ", trSuf:"-at"},
  {ar:"نَحْنُ", tr:"naḥnu", es:"nosotros", suf:"ْنَا", trSuf:"-nā"},
  {ar:"أَنْتُمْ", tr:"antum", es:"ustedes", suf:"ْتُمْ", trSuf:"-tum"},
  {ar:"هُمْ", tr:"hum", es:"ellos", suf:"ُوا", trSuf:"-ū"}
],

verbos: [
  {raiz:"ك-ت-ب", base:"كَتَبَ", tr:"kataba", es:"escribir",
   f:["كَتَبْتُ","كَتَبْتَ","كَتَبْتِ","كَتَبَ","كَتَبَتْ","كَتَبْنَا","كَتَبْتُمْ","كَتَبُوا"],
   ftr:["katabtu","katabta","katabti","kataba","katabat","katabnā","katabtum","katabū"], n:1},
  {raiz:"د-ر-س", base:"دَرَسَ", tr:"darasa", es:"estudiar",
   f:["دَرَسْتُ","دَرَسْتَ","دَرَسْتِ","دَرَسَ","دَرَسَتْ","دَرَسْنَا","دَرَسْتُمْ","دَرَسُوا"],
   ftr:["darastu","darasta","darasti","darasa","darasat","darasnā","darastum","darasū"], n:1},
  {raiz:"ذ-ه-ب", base:"ذَهَبَ", tr:"dhahaba", es:"ir / irse",
   f:["ذَهَبْتُ","ذَهَبْتَ","ذَهَبْتِ","ذَهَبَ","ذَهَبَتْ","ذَهَبْنَا","ذَهَبْتُمْ","ذَهَبُوا"],
   ftr:["dhahabtu","dhahabta","dhahabti","dhahaba","dhahabat","dhahabnā","dhahabtum","dhahabū"], n:2},
  {raiz:"أ-ك-ل", base:"أَكَلَ", tr:"akala", es:"comer",
   f:["أَكَلْتُ","أَكَلْتَ","أَكَلْتِ","أَكَلَ","أَكَلَتْ","أَكَلْنَا","أَكَلْتُمْ","أَكَلُوا"],
   ftr:["akaltu","akalta","akalti","akala","akalat","akalnā","akaltum","akalū"], n:2},
  {raiz:"ش-ر-ب", base:"شَرِبَ", tr:"shariba", es:"beber",
   f:["شَرِبْتُ","شَرِبْتَ","شَرِبْتِ","شَرِبَ","شَرِبَتْ","شَرِبْنَا","شَرِبْتُمْ","شَرِبُوا"],
   ftr:["shribtu","sharibta","sharibti","shariba","sharibat","sharibnā","sharibtum","sharibū"], n:2,
   nota:"la vocal del medio es 'i' y no cambia al conjugar"},
  {raiz:"ف-ت-ح", base:"فَتَحَ", tr:"fataḥa", es:"abrir",
   f:["فَتَحْتُ","فَتَحْتَ","فَتَحْتِ","فَتَحَ","فَتَحَتْ","فَتَحْنَا","فَتَحْتُمْ","فَتَحُوا"],
   ftr:["fataḥtu","fataḥta","fataḥti","fataḥa","fataḥat","fataḥnā","fataḥtum","fataḥū"], n:3},
  {raiz:"س-م-ع", base:"سَمِعَ", tr:"samiʿa", es:"oír / escuchar",
   f:["سَمِعْتُ","سَمِعْتَ","سَمِعْتِ","سَمِعَ","سَمِعَتْ","سَمِعْنَا","سَمِعْتُمْ","سَمِعُوا"],
   ftr:["samiʿtu","samiʿta","samiʿti","samiʿa","samiʿat","samiʿnā","samiʿtum","samiʿū"], n:3}
],

/* ---------- NÚMEROS ---------- */
numeros: [
  {n:1, cifra:"١", ar:"وَاحِد", tr:"wāḥid"},
  {n:2, cifra:"٢", ar:"اِثْنَان", tr:"ithnān"},
  {n:3, cifra:"٣", ar:"ثَلَاثَة", tr:"thalātha"},
  {n:4, cifra:"٤", ar:"أَرْبَعَة", tr:"arbaʿa"},
  {n:5, cifra:"٥", ar:"خَمْسَة", tr:"khamsa"},
  {n:6, cifra:"٦", ar:"سِتَّة", tr:"sitta"},
  {n:7, cifra:"٧", ar:"سَبْعَة", tr:"sabʿa"},
  {n:8, cifra:"٨", ar:"ثَمَانِيَة", tr:"thamāniya"},
  {n:9, cifra:"٩", ar:"تِسْعَة", tr:"tisʿa"},
  {n:10,cifra:"١٠",ar:"عَشَرَة", tr:"ʿashara"},
  {n:11,cifra:"١١",ar:"أَحَدَ عَشَرَ", tr:"aḥada ʿashara"},
  {n:12,cifra:"١٢",ar:"اِثْنَا عَشَرَ", tr:"ithnā ʿashara"},
  {n:15,cifra:"١٥",ar:"خَمْسَةَ عَشَرَ", tr:"khamsata ʿashara"},
  {n:20,cifra:"٢٠",ar:"عِشْرُونَ", tr:"ʿishrūna"},
  {n:0, cifra:"٠", ar:"صِفْر", tr:"ṣifr"}
],

colores: [
  {m:"أَحْمَر", mtr:"aḥmar", f:"حَمْرَاء", ftr:"ḥamrāʼ", es:"rojo"},
  {m:"أَزْرَق", mtr:"azraq", f:"زَرْقَاء", ftr:"zarqāʼ", es:"azul"},
  {m:"أَخْضَر", mtr:"akhḍar", f:"خَضْرَاء", ftr:"khaḍrāʼ", es:"verde"},
  {m:"أَصْفَر", mtr:"aṣfar", f:"صَفْرَاء", ftr:"ṣafrāʼ", es:"amarillo"},
  {m:"أَبْيَض", mtr:"abyaḍ", f:"بَيْضَاء", ftr:"bayḍāʼ", es:"blanco"},
  {m:"أَسْوَد", mtr:"aswad", f:"سَوْدَاء", ftr:"sawdāʼ", es:"negro"}
],

/* ---------- GRAMÁTICA ---------- */
gramatica: [
  {q:"¿Cómo se escribe 'la casa es grande'?", ops:["اَلْبَيْتُ كَبِيرٌ","اَلْبَيْتُ الْكَبِيرُ","بَيْتٌ كَبِيرٌ","بَيْتُ كَبِير"], ok:0, ar:true, tema:"Frase nominal",
   nota:"Frase nominal = <b>sujeto definido + predicado indefinido</b>. <i>al-baytu kabīrun</i>. Si pones artículo en las dos, dices 'la casa grande' y no es una frase.", n:1},
  {q:"اَلْبَيْتُ الْكَبِيرُ significa…", ops:["la casa grande","la casa es grande","una casa grande","¿es grande la casa?"], ok:0, tema:"Frase nominal",
   nota:"Los dos definidos → es solo un grupo de palabras (sustantivo + adjetivo), no una frase.", n:2},
  {q:"En árabe, el verbo 'ser/estar' en PRESENTE…", ops:["no existe, se omite","es كَانَ","es لَيْسَ","es هُوَ"], ok:0, tema:"Frase nominal",
   nota:"Solo existe en pasado (كَانَ) y futuro. En presente simplemente se omite. Menos conjugación que memorizar.", n:1},
  {q:"Para negar 'la casa es grande' se usa…", ops:["لَيْسَ الْبَيْتُ كَبِيرًا","لَا الْبَيْتُ كَبِيرٌ","مَا الْبَيْتُ كَبِيرٌ","الْبَيْتُ لَا كَبِيرٌ"], ok:0, ar:true, tema:"Frase nominal",
   nota:"<b>لَيْسَ</b> va delante y el predicado cambia su tanwin de -un a <b>-an</b>: كَبِيرٌ → كَبِيرًا.", n:3},
  {q:"¿Cuántos artículos determinados tiene el árabe?", ops:["Uno solo: الـ","Dos: masculino y femenino","Tres, como el alemán","Ninguno"], ok:0, tema:"Artículo",
   nota:"<b>الـ</b> sirve para masculino, femenino, singular y plural. Siempre pegado, nunca separado.", n:1},
  {q:"Una palabra con artículo الـ…", ops:["nunca lleva tanwin","siempre lleva tanwin","lleva tanwin -an","depende del género"], ok:0, tema:"Artículo",
   nota:"O artículo, O tanwin. Nunca los dos: ❌ اَلْكِتَابٌ · ✅ اَلْكِتَابُ", n:2},
  {q:"El artículo indefinido ('un/una') en árabe es…", ops:["el tanwin","إِنْ","وَاحِد","no se marca"], ok:0, tema:"Artículo",
   nota:"كِتَابٌ (<i>kitābun</i>) ya significa 'un libro'. El tanwin ES la marca de indefinido.", n:2},
  {q:"Si la primera letra de la palabra lleva SHADDA y la ل no tiene vocal, la letra es…", ops:["solar (la 'l' no se pronuncia)","lunar (la 'l' sí se pronuncia)","siempre femenina","imposible de saber"], ok:0, tema:"Solar/Lunar",
   nota:"La shadda es tu pista visual gratis en texto vocalizado. اَلشَّمْس → <i>ash-shams</i>.", n:2},
  {q:"¿Cuántas letras solares hay?", ops:["14","10","28","7"], ok:0, tema:"Solar/Lunar",
   nota:"14 solares y 14 lunares. Aprende solo una lista; la otra es 'todo lo demás'.", n:2},
  {q:"El truco fonético para saber si una letra es SOLAR es…", ops:["la punta de la lengua toca cerca de donde se hace la 'l'","la letra tiene puntos","la letra es enfática","empieza la palabra"], ok:0, tema:"Solar/Lunar",
   nota:"ت د س ش ن ر ل se hacen con la punta de la lengua arriba → la 'l' se contagia y se funde. Labios o garganta (ب م ق ك ح ع) → lunares.", n:3},
  {q:"La marca de femenino más frecuente al final de palabra es…", ops:["ة (ta marbuta)","ا (alif)","ي (yāʼ)","ن (nūn)"], ok:0, tema:"Género",
   nota:"مُدَرِّس → مُدَرِّسَة. Funciona casi como nuestra '-a'.", n:1},
  {q:"شَمْس ('sol') es…", ops:["femenino (irregular)","masculino","neutro","depende"], ok:0, tema:"Género",
   nota:"Femenino sin ة. Truco: los elementos de la naturaleza (شمس، نار، أرض، ريح) y las partes del cuerpo <b>pares</b> (يد، عين، أذن، رجل) son femeninos.", n:3},
  {q:"يَد ('mano') es…", ops:["femenino (irregular)","masculino","neutro","ambos"], ok:0, tema:"Género",
   nota:"Partes del cuerpo que van en pareja → femeninas.", n:3},
  {q:"El adjetivo en árabe va…", ops:["detrás del sustantivo","delante del sustantivo","al final de la frase","donde quieras"], ok:0, tema:"Género",
   nota:"Y copia <b>género + definición + caso</b>: بَيْتٌ كَبِيرٌ / اَلْبَيْتُ الْكَبِيرُ.", n:1},
  {q:"'tú' dirigido a una MUJER se dice…", ops:["أَنْتِ","أَنْتَ","أَنْتُمْ","أَنَا"], ok:0, ar:true, tema:"Pronombres",
   nota:"Mismas letras (أنت), solo cambia la marquita: fatha = a un hombre, <b>kasra</b> = a una mujer.", n:1},
  {q:"Los posesivos ('mi, tu, su') en árabe…", ops:["se pegan al final del sustantivo","van delante","son palabras sueltas","no existen"], ok:0, tema:"Pronombres",
   nota:"كِتَابِي (mi libro), كِتَابُكَ (tu libro), كِتَابُهَا (su libro de ella).", n:1},
  {q:"Una palabra con sufijo posesivo…", ops:["ya es definida: no lleva artículo ni tanwin","lleva artículo obligatorio","lleva tanwin","cambia de género"], ok:0, tema:"Pronombres",
   nota:"❌ اَلْكِتَابِي · ✅ كِتَابِي", n:2},
  {q:"هٰذَا بَيْتٌ significa…", ops:["esto es una casa","esta casa","la casa","¿es una casa?"], ok:0, tema:"Demostrativos",
   nota:"Sustantivo <b>indefinido</b> → hay verbo 'ser' invisible → frase completa.", n:2},
  {q:"هٰذَا الْبَيْتُ significa…", ops:["esta casa (grupo, no frase)","esto es una casa","la casa es esta","¿esta casa?"], ok:0, tema:"Demostrativos",
   nota:"Con الـ el demostrativo se pega como adjetivo. Para afirmar algo, <b>quita el الـ</b> o añade un predicado.", n:3},
  {q:"El demostrativo para femenino cercano es…", ops:["هٰذِهِ","هٰذَا","ذٰلِكَ","تِلْكَ"], ok:0, ar:true, tema:"Demostrativos",
   nota:"هٰذَا (m. cerca) · هٰذِهِ (f. cerca) · ذٰلِكَ (m. lejos) · تِلْكَ (f. lejos).", n:1},
  {q:"'¿dónde?' se dice…", ops:["أَيْنَ","مَتَى","كَيْفَ","لِمَاذَا"], ok:0, ar:true, tema:"Preguntas",
   nota:"مَا=qué · مَنْ=quién · أَيْنَ=dónde · كَيْفَ=cómo · مَتَى=cuándo · لِمَاذَا=por qué · كَمْ=cuánto · هَلْ=¿acaso?", n:1},
  {q:"Para una pregunta de SÍ o NO se antepone…", ops:["هَلْ","مَا","مَنْ","لَا"], ok:0, ar:true, tema:"Preguntas",
   nota:"<b>هَلْ</b> delante de una frase normal, sin cambiar nada más. Respuestas: نَعَمْ / لَا.", n:1},
  {q:"مَا vs مَاذَا: ¿cuál va delante de un VERBO?", ops:["مَاذَا","مَا","las dos","ninguna"], ok:0, tema:"Preguntas",
   nota:"<b>مَا</b> ante sustantivo (مَا هٰذَا؟) · <b>مَاذَا</b> ante verbo (مَاذَا كَتَبْتَ؟).", n:3},
  {q:"En árabe no existe el verbo 'tener'. Se usa…", ops:["عِنْدَ + pronombre","كَانَ","هُوَ","لَيْسَ"], ok:0, tema:"Números",
   nota:"عِنْدِي = 'tengo' (literalmente 'junto a mí'). عِنْدِي، عِنْدَكَ، عِنْدَهُ، عِنْدَهَا.", n:2},
  {q:"Después de كَمْ ('cuántos'), el sustantivo va…", ops:["en singular con tanwin -an","en plural","en dual","sin marca"], ok:0, tema:"Números",
   nota:"كَمْ كِتَابًا عِنْدَكَ؟ — al revés de lo que pide tu instinto español.", n:3},
  {q:"Las cifras árabes orientales (١٩٩٥) se leen…", ops:["de izquierda a derecha","de derecha a izquierda","de arriba abajo","al revés"], ok:0, tema:"Números",
   nota:"Es lo único de la página que va 'hacia el otro lado'. ١٩٩٥ = 1995.", n:2},
  {q:"Casi toda palabra árabe se construye sobre…", ops:["una raíz de 3 consonantes","un prefijo","una vocal larga","un artículo"], ok:0, tema:"Raíces",
   nota:"ك-ت-ب → كَتَبَ (escribió), كِتَاب (libro), كَاتِب (escritor), مَكْتَب (oficina), مَكْتَبَة (biblioteca).", n:1},
  {q:"Si una palabra empieza por مَـ, normalmente designa…", ops:["un lugar","una persona","una acción","un adjetivo"], ok:0, tema:"Raíces",
   nota:"مَكْتَب (oficina), مَدْرَسَة (escuela), مَطْبَخ (cocina), مَطْعَم (restaurante).", n:2},
  {q:"¿Qué raíz comparten مَكْتَبَة، كَاتِب y كَتَبَ?", ops:["ك-ت-ب","م-ك-ت","ك-ا-ب","ت-ب-ة"], ok:0, tema:"Raíces",
   nota:"Las vocales largas y la ة NO forman parte de la raíz. Quédate con el esqueleto consonántico.", n:2},
  {q:"La forma que aparece en el diccionario árabe es…", ops:["3ª persona masc. singular del pasado","el infinitivo","la 1ª persona","el participio"], ok:0, tema:"Verbos",
   nota:"كَتَبَ = 'él escribió'. No existe infinitivo como nuestro 'escribir'.", n:2},
  {q:"Para negar el pasado se pone delante del verbo…", ops:["مَا","لَا","لَيْسَ","هَلْ"], ok:0, ar:true, tema:"Verbos",
   nota:"مَا كَتَبْتُ = 'no escribí'. Ojo: este مَا (no) es distinto del مَا (qué) — lo distingues por la posición.", n:2},
  {q:"En una frase con verbo, el orden normal en árabe es…", ops:["verbo → sujeto → complemento","sujeto → verbo → complemento","complemento → verbo → sujeto","sujeto → complemento → verbo"], ok:0, tema:"Verbos",
   nota:"كَتَبَ الْوَلَدُ دَرْسَهُ. Al revés que en español.", n:3},
  {q:"كَتَبُوا lleva un alif final que…", ops:["no se pronuncia","suena 'a'","dobla la vocal","marca femenino"], ok:0, tema:"Verbos",
   nota:"Alif mudo, puro adorno ortográfico de la terminación -ū de 'ellos'. Se lee <i>katabū</i>.", n:3},
  {q:"La shadda sobre una consonante significa que…", ops:["se pronuncia doble","no lleva vocal","es femenina","es solar"], ok:0, tema:"Escritura",
   nota:"Y <b>cambia el significado</b>: دَرَسَ (estudió) vs دَرَّسَ (enseñó).", n:1},
  {q:"El sukun (circulito) significa que la letra…", ops:["no lleva vocal","lleva 'u'","se dobla","es femenina"], ok:0, tema:"Escritura",
   nota:"Se pronuncia 'seca', pegada a la anterior: بِنْت → <i>bint</i>.", n:1},
  {q:"¿Cuántas letras NO se conectan con la siguiente?", ops:["6: ا د ذ ر ز و","4","28","14"], ok:0, tema:"Escritura",
   nota:"Después de ellas siempre queda un huequito y la próxima letra empieza 'de nuevo'.", n:2},
  {q:"La 'a' larga (ā) se forma con…", ops:["fatha + ا","damma + و","kasra + ي","shadda"], ok:0, tema:"Escritura",
   nota:"ā = fatha+alif · ū = damma+wāw · ī = kasra+yāʼ. بَاب، نُور، فِيل.", n:1},
  {q:"La ligadura obligatoria de lām + alif se escribe…", ops:["لا","لى","ال","لأ"], ok:0, ar:true, tema:"Escritura",
   nota:"Se lee 'la'. Apréndela como una unidad: la verás por todos lados.", n:2}
]

};
